// Code generated by mockery v2.42.1. DO NOT EDIT.

package serializer

import (
	domain "github.com/cloudogu/k8s-blueprint-operator/v2/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockBlueprintMaskSerializer is an autogenerated mock type for the BlueprintMaskSerializer type
type MockBlueprintMaskSerializer struct {
	mock.Mock
}

type MockBlueprintMaskSerializer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlueprintMaskSerializer) EXPECT() *MockBlueprintMaskSerializer_Expecter {
	return &MockBlueprintMaskSerializer_Expecter{mock: &_m.Mock}
}

// Deserialize provides a mock function with given fields: rawBlueprintMask
func (_m *MockBlueprintMaskSerializer) Deserialize(rawBlueprintMask string) (domain.BlueprintMask, error) {
	ret := _m.Called(rawBlueprintMask)

	if len(ret) == 0 {
		panic("no return value specified for Deserialize")
	}

	var r0 domain.BlueprintMask
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (domain.BlueprintMask, error)); ok {
		return rf(rawBlueprintMask)
	}
	if rf, ok := ret.Get(0).(func(string) domain.BlueprintMask); ok {
		r0 = rf(rawBlueprintMask)
	} else {
		r0 = ret.Get(0).(domain.BlueprintMask)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(rawBlueprintMask)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBlueprintMaskSerializer_Deserialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deserialize'
type MockBlueprintMaskSerializer_Deserialize_Call struct {
	*mock.Call
}

// Deserialize is a helper method to define mock.On call
//   - rawBlueprintMask string
func (_e *MockBlueprintMaskSerializer_Expecter) Deserialize(rawBlueprintMask interface{}) *MockBlueprintMaskSerializer_Deserialize_Call {
	return &MockBlueprintMaskSerializer_Deserialize_Call{Call: _e.mock.On("Deserialize", rawBlueprintMask)}
}

func (_c *MockBlueprintMaskSerializer_Deserialize_Call) Run(run func(rawBlueprintMask string)) *MockBlueprintMaskSerializer_Deserialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockBlueprintMaskSerializer_Deserialize_Call) Return(_a0 domain.BlueprintMask, _a1 error) *MockBlueprintMaskSerializer_Deserialize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBlueprintMaskSerializer_Deserialize_Call) RunAndReturn(run func(string) (domain.BlueprintMask, error)) *MockBlueprintMaskSerializer_Deserialize_Call {
	_c.Call.Return(run)
	return _c
}

// Serialize provides a mock function with given fields: mask
func (_m *MockBlueprintMaskSerializer) Serialize(mask domain.BlueprintMask) (string, error) {
	ret := _m.Called(mask)

	if len(ret) == 0 {
		panic("no return value specified for Serialize")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.BlueprintMask) (string, error)); ok {
		return rf(mask)
	}
	if rf, ok := ret.Get(0).(func(domain.BlueprintMask) string); ok {
		r0 = rf(mask)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(domain.BlueprintMask) error); ok {
		r1 = rf(mask)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBlueprintMaskSerializer_Serialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serialize'
type MockBlueprintMaskSerializer_Serialize_Call struct {
	*mock.Call
}

// Serialize is a helper method to define mock.On call
//   - mask domain.BlueprintMask
func (_e *MockBlueprintMaskSerializer_Expecter) Serialize(mask interface{}) *MockBlueprintMaskSerializer_Serialize_Call {
	return &MockBlueprintMaskSerializer_Serialize_Call{Call: _e.mock.On("Serialize", mask)}
}

func (_c *MockBlueprintMaskSerializer_Serialize_Call) Run(run func(mask domain.BlueprintMask)) *MockBlueprintMaskSerializer_Serialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.BlueprintMask))
	})
	return _c
}

func (_c *MockBlueprintMaskSerializer_Serialize_Call) Return(_a0 string, _a1 error) *MockBlueprintMaskSerializer_Serialize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBlueprintMaskSerializer_Serialize_Call) RunAndReturn(run func(domain.BlueprintMask) (string, error)) *MockBlueprintMaskSerializer_Serialize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBlueprintMaskSerializer creates a new instance of MockBlueprintMaskSerializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlueprintMaskSerializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlueprintMaskSerializer {
	mock := &MockBlueprintMaskSerializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
