apiVersion: k8s.cloudogu.com/v1
kind: Blueprint
metadata:
  labels:
    app.kubernetes.io/name: blueprint
    app.kubernetes.io/instance: blueprint-sample
    app.kubernetes.io/part-of: k8s-blueprint-operator
    app.kubernetes.io/created-by: k8s-blueprint-operator
  name: blueprint-nexus-3-59-0-2-config-change
spec:
  blueprint: |
    {
      "blueprintApi":"v2",
      "dogus":[
        {
          "name":"official/nexus",
          "version":"3.59.0-2",
          "targetState":"present",
          "platformConfig": {
            "resource": {
              "minVolumeSize": "6Gi"
            },
            "reverseProxy": {
              "maxBodySize": "2Gi"
            }
          }
        },
        {
          "name":"official/cas",
          "version":"6.6.15-1",
          "targetState":"present"
        },
        {
          "name":"official/postfix",
          "version":"3.8.4-1",
          "targetState":"present"
        },
        {
          "name":"k8s/nginx-ingress",
          "version":"1.6.4-4",
          "targetState":"present"
        },
        {
          "name":"k8s/nginx-static",
          "version":"1.23.1-6",
          "targetState":"present"
        }
      ]
    }
  blueprintMask: |
    {"blueprintMaskApi":"v1"}
  ignoreDoguHealth: false
  allowDoguNamespaceSwitch: false
