// Code generated by mockery v2.20.0. DO NOT EDIT.

package common

import mock "github.com/stretchr/testify/mock"

// MockRegistryConfigKey is an autogenerated mock type for the RegistryConfigKey type
type MockRegistryConfigKey struct {
	mock.Mock
}

type MockRegistryConfigKey_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistryConfigKey) EXPECT() *MockRegistryConfigKey_Expecter {
	return &MockRegistryConfigKey_Expecter{mock: &_m.Mock}
}

type mockConstructorTestingTNewMockRegistryConfigKey interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRegistryConfigKey creates a new instance of MockRegistryConfigKey. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRegistryConfigKey(t mockConstructorTestingTNewMockRegistryConfigKey) *MockRegistryConfigKey {
	mock := &MockRegistryConfigKey{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
