// Code generated by mockery v2.20.0. DO NOT EDIT.

package dogucr

import (
	context "context"

	corev1 "k8s.io/api/core/v1"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	mock "github.com/stretchr/testify/mock"

	types "k8s.io/apimachinery/pkg/types"

	v1 "k8s.io/client-go/applyconfigurations/core/v1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// MockPvcInterface is an autogenerated mock type for the PvcInterface type
type MockPvcInterface struct {
	mock.Mock
}

type MockPvcInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPvcInterface) EXPECT() *MockPvcInterface_Expecter {
	return &MockPvcInterface_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: ctx, persistentVolumeClaim, opts
func (_m *MockPvcInterface) Apply(ctx context.Context, persistentVolumeClaim *v1.PersistentVolumeClaimApplyConfiguration, opts metav1.ApplyOptions) (*corev1.PersistentVolumeClaim, error) {
	ret := _m.Called(ctx, persistentVolumeClaim, opts)

	var r0 *corev1.PersistentVolumeClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.PersistentVolumeClaimApplyConfiguration, metav1.ApplyOptions) (*corev1.PersistentVolumeClaim, error)); ok {
		return rf(ctx, persistentVolumeClaim, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.PersistentVolumeClaimApplyConfiguration, metav1.ApplyOptions) *corev1.PersistentVolumeClaim); ok {
		r0 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PersistentVolumeClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.PersistentVolumeClaimApplyConfiguration, metav1.ApplyOptions) error); ok {
		r1 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPvcInterface_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockPvcInterface_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - ctx context.Context
//   - persistentVolumeClaim *v1.PersistentVolumeClaimApplyConfiguration
//   - opts metav1.ApplyOptions
func (_e *MockPvcInterface_Expecter) Apply(ctx interface{}, persistentVolumeClaim interface{}, opts interface{}) *MockPvcInterface_Apply_Call {
	return &MockPvcInterface_Apply_Call{Call: _e.mock.On("Apply", ctx, persistentVolumeClaim, opts)}
}

func (_c *MockPvcInterface_Apply_Call) Run(run func(ctx context.Context, persistentVolumeClaim *v1.PersistentVolumeClaimApplyConfiguration, opts metav1.ApplyOptions)) *MockPvcInterface_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.PersistentVolumeClaimApplyConfiguration), args[2].(metav1.ApplyOptions))
	})
	return _c
}

func (_c *MockPvcInterface_Apply_Call) Return(result *corev1.PersistentVolumeClaim, err error) *MockPvcInterface_Apply_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockPvcInterface_Apply_Call) RunAndReturn(run func(context.Context, *v1.PersistentVolumeClaimApplyConfiguration, metav1.ApplyOptions) (*corev1.PersistentVolumeClaim, error)) *MockPvcInterface_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyStatus provides a mock function with given fields: ctx, persistentVolumeClaim, opts
func (_m *MockPvcInterface) ApplyStatus(ctx context.Context, persistentVolumeClaim *v1.PersistentVolumeClaimApplyConfiguration, opts metav1.ApplyOptions) (*corev1.PersistentVolumeClaim, error) {
	ret := _m.Called(ctx, persistentVolumeClaim, opts)

	var r0 *corev1.PersistentVolumeClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.PersistentVolumeClaimApplyConfiguration, metav1.ApplyOptions) (*corev1.PersistentVolumeClaim, error)); ok {
		return rf(ctx, persistentVolumeClaim, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.PersistentVolumeClaimApplyConfiguration, metav1.ApplyOptions) *corev1.PersistentVolumeClaim); ok {
		r0 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PersistentVolumeClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.PersistentVolumeClaimApplyConfiguration, metav1.ApplyOptions) error); ok {
		r1 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPvcInterface_ApplyStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyStatus'
type MockPvcInterface_ApplyStatus_Call struct {
	*mock.Call
}

// ApplyStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - persistentVolumeClaim *v1.PersistentVolumeClaimApplyConfiguration
//   - opts metav1.ApplyOptions
func (_e *MockPvcInterface_Expecter) ApplyStatus(ctx interface{}, persistentVolumeClaim interface{}, opts interface{}) *MockPvcInterface_ApplyStatus_Call {
	return &MockPvcInterface_ApplyStatus_Call{Call: _e.mock.On("ApplyStatus", ctx, persistentVolumeClaim, opts)}
}

func (_c *MockPvcInterface_ApplyStatus_Call) Run(run func(ctx context.Context, persistentVolumeClaim *v1.PersistentVolumeClaimApplyConfiguration, opts metav1.ApplyOptions)) *MockPvcInterface_ApplyStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.PersistentVolumeClaimApplyConfiguration), args[2].(metav1.ApplyOptions))
	})
	return _c
}

func (_c *MockPvcInterface_ApplyStatus_Call) Return(result *corev1.PersistentVolumeClaim, err error) *MockPvcInterface_ApplyStatus_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockPvcInterface_ApplyStatus_Call) RunAndReturn(run func(context.Context, *v1.PersistentVolumeClaimApplyConfiguration, metav1.ApplyOptions) (*corev1.PersistentVolumeClaim, error)) *MockPvcInterface_ApplyStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, persistentVolumeClaim, opts
func (_m *MockPvcInterface) Create(ctx context.Context, persistentVolumeClaim *corev1.PersistentVolumeClaim, opts metav1.CreateOptions) (*corev1.PersistentVolumeClaim, error) {
	ret := _m.Called(ctx, persistentVolumeClaim, opts)

	var r0 *corev1.PersistentVolumeClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.PersistentVolumeClaim, metav1.CreateOptions) (*corev1.PersistentVolumeClaim, error)); ok {
		return rf(ctx, persistentVolumeClaim, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.PersistentVolumeClaim, metav1.CreateOptions) *corev1.PersistentVolumeClaim); ok {
		r0 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PersistentVolumeClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *corev1.PersistentVolumeClaim, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPvcInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPvcInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - persistentVolumeClaim *corev1.PersistentVolumeClaim
//   - opts metav1.CreateOptions
func (_e *MockPvcInterface_Expecter) Create(ctx interface{}, persistentVolumeClaim interface{}, opts interface{}) *MockPvcInterface_Create_Call {
	return &MockPvcInterface_Create_Call{Call: _e.mock.On("Create", ctx, persistentVolumeClaim, opts)}
}

func (_c *MockPvcInterface_Create_Call) Run(run func(ctx context.Context, persistentVolumeClaim *corev1.PersistentVolumeClaim, opts metav1.CreateOptions)) *MockPvcInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*corev1.PersistentVolumeClaim), args[2].(metav1.CreateOptions))
	})
	return _c
}

func (_c *MockPvcInterface_Create_Call) Return(_a0 *corev1.PersistentVolumeClaim, _a1 error) *MockPvcInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPvcInterface_Create_Call) RunAndReturn(run func(context.Context, *corev1.PersistentVolumeClaim, metav1.CreateOptions) (*corev1.PersistentVolumeClaim, error)) *MockPvcInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *MockPvcInterface) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPvcInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPvcInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.DeleteOptions
func (_e *MockPvcInterface_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *MockPvcInterface_Delete_Call {
	return &MockPvcInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *MockPvcInterface_Delete_Call) Run(run func(ctx context.Context, name string, opts metav1.DeleteOptions)) *MockPvcInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.DeleteOptions))
	})
	return _c
}

func (_c *MockPvcInterface_Delete_Call) Return(_a0 error) *MockPvcInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPvcInterface_Delete_Call) RunAndReturn(run func(context.Context, string, metav1.DeleteOptions) error) *MockPvcInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function with given fields: ctx, opts, listOpts
func (_m *MockPvcInterface) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	ret := _m.Called(ctx, opts, listOpts)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error); ok {
		r0 = rf(ctx, opts, listOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPvcInterface_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type MockPvcInterface_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.DeleteOptions
//   - listOpts metav1.ListOptions
func (_e *MockPvcInterface_Expecter) DeleteCollection(ctx interface{}, opts interface{}, listOpts interface{}) *MockPvcInterface_DeleteCollection_Call {
	return &MockPvcInterface_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", ctx, opts, listOpts)}
}

func (_c *MockPvcInterface_DeleteCollection_Call) Run(run func(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions)) *MockPvcInterface_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.DeleteOptions), args[2].(metav1.ListOptions))
	})
	return _c
}

func (_c *MockPvcInterface_DeleteCollection_Call) Return(_a0 error) *MockPvcInterface_DeleteCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPvcInterface_DeleteCollection_Call) RunAndReturn(run func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error) *MockPvcInterface_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *MockPvcInterface) Get(ctx context.Context, name string, opts metav1.GetOptions) (*corev1.PersistentVolumeClaim, error) {
	ret := _m.Called(ctx, name, opts)

	var r0 *corev1.PersistentVolumeClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) (*corev1.PersistentVolumeClaim, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) *corev1.PersistentVolumeClaim); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PersistentVolumeClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, metav1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPvcInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPvcInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.GetOptions
func (_e *MockPvcInterface_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *MockPvcInterface_Get_Call {
	return &MockPvcInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *MockPvcInterface_Get_Call) Run(run func(ctx context.Context, name string, opts metav1.GetOptions)) *MockPvcInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.GetOptions))
	})
	return _c
}

func (_c *MockPvcInterface_Get_Call) Return(_a0 *corev1.PersistentVolumeClaim, _a1 error) *MockPvcInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPvcInterface_Get_Call) RunAndReturn(run func(context.Context, string, metav1.GetOptions) (*corev1.PersistentVolumeClaim, error)) *MockPvcInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *MockPvcInterface) List(ctx context.Context, opts metav1.ListOptions) (*corev1.PersistentVolumeClaimList, error) {
	ret := _m.Called(ctx, opts)

	var r0 *corev1.PersistentVolumeClaimList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (*corev1.PersistentVolumeClaimList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) *corev1.PersistentVolumeClaimList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PersistentVolumeClaimList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPvcInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPvcInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *MockPvcInterface_Expecter) List(ctx interface{}, opts interface{}) *MockPvcInterface_List_Call {
	return &MockPvcInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *MockPvcInterface_List_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *MockPvcInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *MockPvcInterface_List_Call) Return(_a0 *corev1.PersistentVolumeClaimList, _a1 error) *MockPvcInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPvcInterface_List_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (*corev1.PersistentVolumeClaimList, error)) *MockPvcInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, name, pt, data, opts, subresources
func (_m *MockPvcInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*corev1.PersistentVolumeClaim, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, pt, data, opts)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *corev1.PersistentVolumeClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) (*corev1.PersistentVolumeClaim, error)); ok {
		return rf(ctx, name, pt, data, opts, subresources...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) *corev1.PersistentVolumeClaim); ok {
		r0 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PersistentVolumeClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) error); ok {
		r1 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPvcInterface_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockPvcInterface_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - pt types.PatchType
//   - data []byte
//   - opts metav1.PatchOptions
//   - subresources ...string
func (_e *MockPvcInterface_Expecter) Patch(ctx interface{}, name interface{}, pt interface{}, data interface{}, opts interface{}, subresources ...interface{}) *MockPvcInterface_Patch_Call {
	return &MockPvcInterface_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, name, pt, data, opts}, subresources...)...)}
}

func (_c *MockPvcInterface_Patch_Call) Run(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string)) *MockPvcInterface_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(types.PatchType), args[3].([]byte), args[4].(metav1.PatchOptions), variadicArgs...)
	})
	return _c
}

func (_c *MockPvcInterface_Patch_Call) Return(result *corev1.PersistentVolumeClaim, err error) *MockPvcInterface_Patch_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockPvcInterface_Patch_Call) RunAndReturn(run func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) (*corev1.PersistentVolumeClaim, error)) *MockPvcInterface_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, persistentVolumeClaim, opts
func (_m *MockPvcInterface) Update(ctx context.Context, persistentVolumeClaim *corev1.PersistentVolumeClaim, opts metav1.UpdateOptions) (*corev1.PersistentVolumeClaim, error) {
	ret := _m.Called(ctx, persistentVolumeClaim, opts)

	var r0 *corev1.PersistentVolumeClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.PersistentVolumeClaim, metav1.UpdateOptions) (*corev1.PersistentVolumeClaim, error)); ok {
		return rf(ctx, persistentVolumeClaim, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.PersistentVolumeClaim, metav1.UpdateOptions) *corev1.PersistentVolumeClaim); ok {
		r0 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PersistentVolumeClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *corev1.PersistentVolumeClaim, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPvcInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPvcInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - persistentVolumeClaim *corev1.PersistentVolumeClaim
//   - opts metav1.UpdateOptions
func (_e *MockPvcInterface_Expecter) Update(ctx interface{}, persistentVolumeClaim interface{}, opts interface{}) *MockPvcInterface_Update_Call {
	return &MockPvcInterface_Update_Call{Call: _e.mock.On("Update", ctx, persistentVolumeClaim, opts)}
}

func (_c *MockPvcInterface_Update_Call) Run(run func(ctx context.Context, persistentVolumeClaim *corev1.PersistentVolumeClaim, opts metav1.UpdateOptions)) *MockPvcInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*corev1.PersistentVolumeClaim), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *MockPvcInterface_Update_Call) Return(_a0 *corev1.PersistentVolumeClaim, _a1 error) *MockPvcInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPvcInterface_Update_Call) RunAndReturn(run func(context.Context, *corev1.PersistentVolumeClaim, metav1.UpdateOptions) (*corev1.PersistentVolumeClaim, error)) *MockPvcInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, persistentVolumeClaim, opts
func (_m *MockPvcInterface) UpdateStatus(ctx context.Context, persistentVolumeClaim *corev1.PersistentVolumeClaim, opts metav1.UpdateOptions) (*corev1.PersistentVolumeClaim, error) {
	ret := _m.Called(ctx, persistentVolumeClaim, opts)

	var r0 *corev1.PersistentVolumeClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.PersistentVolumeClaim, metav1.UpdateOptions) (*corev1.PersistentVolumeClaim, error)); ok {
		return rf(ctx, persistentVolumeClaim, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.PersistentVolumeClaim, metav1.UpdateOptions) *corev1.PersistentVolumeClaim); ok {
		r0 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.PersistentVolumeClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *corev1.PersistentVolumeClaim, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, persistentVolumeClaim, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPvcInterface_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockPvcInterface_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - persistentVolumeClaim *corev1.PersistentVolumeClaim
//   - opts metav1.UpdateOptions
func (_e *MockPvcInterface_Expecter) UpdateStatus(ctx interface{}, persistentVolumeClaim interface{}, opts interface{}) *MockPvcInterface_UpdateStatus_Call {
	return &MockPvcInterface_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, persistentVolumeClaim, opts)}
}

func (_c *MockPvcInterface_UpdateStatus_Call) Run(run func(ctx context.Context, persistentVolumeClaim *corev1.PersistentVolumeClaim, opts metav1.UpdateOptions)) *MockPvcInterface_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*corev1.PersistentVolumeClaim), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *MockPvcInterface_UpdateStatus_Call) Return(_a0 *corev1.PersistentVolumeClaim, _a1 error) *MockPvcInterface_UpdateStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPvcInterface_UpdateStatus_Call) RunAndReturn(run func(context.Context, *corev1.PersistentVolumeClaim, metav1.UpdateOptions) (*corev1.PersistentVolumeClaim, error)) *MockPvcInterface_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *MockPvcInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPvcInterface_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type MockPvcInterface_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *MockPvcInterface_Expecter) Watch(ctx interface{}, opts interface{}) *MockPvcInterface_Watch_Call {
	return &MockPvcInterface_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *MockPvcInterface_Watch_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *MockPvcInterface_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *MockPvcInterface_Watch_Call) Return(_a0 watch.Interface, _a1 error) *MockPvcInterface_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPvcInterface_Watch_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (watch.Interface, error)) *MockPvcInterface_Watch_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockPvcInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockPvcInterface creates a new instance of MockPvcInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockPvcInterface(t mockConstructorTestingTNewMockPvcInterface) *MockPvcInterface {
	mock := &MockPvcInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
