apiVersion: k8s.cloudogu.com/v1
kind: Blueprint
metadata:
  labels:
    app.kubernetes.io/name: blueprint
    app.kubernetes.io/instance: blueprint-sample
    app.kubernetes.io/part-of: k8s-blueprint-operator
    app.kubernetes.io/created-by: k8s-blueprint-operator
  name: blueprint-initial-system
spec:
  blueprint: |
    {
    "blueprintApi":"v2",
    "components": [
      {
        "name":"k8s/k8s-dogu-operator",
        "version":"0.41.0",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-dogu-operator-crd",
        "version":"0.41.0",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-component-operator",
        "version":"0.8.0",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-component-operator-crd",
        "version":"0.8.0",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-etcd",
        "version":"3.5.9-2",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-longhorn",
        "targetState":"present",
        "version":"1.5.1-4",
        "packageConfig":{
          "deployNamespace":"longhorn-system"
        }
      },
      {
        "name":"k8s/k8s-service-discovery",
        "targetState":"present",
        "version":"0.15.0"
      },
      {
        "name":"k8s/k8s-minio",
        "targetState":"absent"
      },
      {
        "name":"k8s/k8s-ces-control",
        "targetState":"absent"
      },
      {
        "name":"k8s/k8s-loki",
        "targetState":"absent"
      },
      {
        "name":"k8s/k8s-prometheus",
        "targetState":"absent"
      },
      {
        "name":"k8s/k8s-snapshot-controller-crd",
        "targetState":"absent"
      },
      {
        "name":"k8s/k8s-snapshot-controller",
        "targetState":"absent"
      },
      {
        "name":"k8s/k8s-cert-manager",
        "targetState":"absent"
      },
      {
        "name":"k8s/k8s-cert-manager-crd",
        "targetState":"absent"
      },
      {
        "name":"k8s/k8s-velero",
        "targetState":"absent"
      },
      {
        "name":"k8s/k8s-backup-operator",
        "targetState":"absent"
      },
      {
        "name":"k8s/k8s-backup-operator-crd",
        "targetState":"absent"
      },
      {
        "name":"k8s/k8s-promtail",
        "targetState":"absent"
      }
    ]
    }
  blueprintMask: |
    {"blueprintMaskApi":"v1"}
  ignoreDoguHealth: false
  allowDoguNamespaceSwitch: false
