apiVersion: k8s.cloudogu.com/v1
kind: Blueprint
metadata:
  labels:
    app.kubernetes.io/name: blueprint
    app.kubernetes.io/instance: cloudogu-blueprint
    app.kubernetes.io/part-of: k8s-blueprint-operator
    app.kubernetes.io/created-by: k8s-blueprint-operator
  name: cloudogu-blueprint
spec:
  blueprint: |
    {
    "blueprintApi":"v2",
    "dogus":[
      {
        "name":"hallowelt/bluespice",
        "version":"4.5.2-2",
        "targetState":"absent"
      },
      {
        "name":"hallowelt/bluespice-collabpadsbackend",
        "version":"1.0.2-2",
        "targetState":"absent"
      },
      {
        "name":"hallowelt/bluespice-mathoid",
        "version":"4.4-3",
        "targetState":"absent"
      },
      {
        "name":"hallowelt/bluespice-opensearch",
        "version":"2.11.1-2",
        "targetState":"absent"
      },
      {
        "name":"hallowelt/bluespice-pdfrenderer",
        "version":"4.4-1",
        "targetState":"absent"
      },
      {
        "name":"hallowelt/drawio",
        "version":"20.3.7-6",
        "targetState":"absent"
      },
      {
        "name":"hallowelt/mongodb",
        "version":"4.4.29-1",
        "targetState":"absent"
      },
    
    
      {
        "name": "itz-bund/easyredmine",
        "version": "13.11.3-3",
        "targetState": "present"
      },
    
    
    
      {
        "name":"official/cas",
        "version":"7.0.8-3",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "10Mi"
          }
        }
      },
      {
        "name":"official/gotenberg",
        "version":"8.12.0-1",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "10Mi"
          }
        }
      },
      {
        "name":"official/jenkins",
        "version":"2.462.3-1",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "20Gi"
          }
        }
      },
      
      {
        "name":"official/cockpit",
        "version":"2.1.0-1",
        "targetState":"present"
      },
      
      {
        "name":"official/ldap",
        "version":"2.6.7-4",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "10Mi"
          }
        }
      },
      {
        "name":"official/ldap-mapper",
        "version":"1.5.0-1",
        "targetState":"present"
      },
      {
        "name":"official/mysql",
        "version":"8.0.38-3",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "1Gi"
          }
        }
      },
      {
        "name":"official/nexus",
        "version":"3.70.2-3",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "20Gi"
          }
        }
      },
      {
        "name":"k8s/nginx-ingress",
        "version":"1.11.1-3",
        "targetState":"present"
      },
      {
        "name":"k8s/nginx-static",
        "version":"1.26.1-7",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "50Mi"
          }
        }
      },
      {
        "name":"official/plantuml",
        "version":"2024.7-1",
        "targetState":"present"
      },
      {
        "name":"official/postfix",
        "version":"3.9.0-3",
        "targetState":"present"
      },
      {
        "name":"official/postgresql",
        "version":"14.12-4",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "10Gi"
          }
        }
      },
      {
        "name":"official/redis",
        "version":"6.2.14-4",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "10Mi"
          }
        }
      },
      {
        "name":"official/redmine",
        "version":"5.1.3-4",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "5Gi"
          }
        }
      },
      {
        "name":"official/scm",
        "version":"3.5.0-1",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "5Gi"
          }
        }
      },
      {
        "name":"official/smeagol",
        "version":"1.7.4-1",
        "targetState":"present"
      },
      {
        "name":"official/sonar",
        "version":"9.9.5-5",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "1Gi"
          }
        }
      },
      {
        "name":"official/swaggerui",
        "version":"5.17.14-1",
        "targetState":"present"
      },
      {
        "name":"official/usermgt",
        "version":"1.16.4-1",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "50Mi"
          }
        }
      },
      {
        "name":"premium/admin",
        "version":"2.12.3-1",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "10Mi"
          }
        }
      },
      {
        "name":"premium/grafana",
        "version":"11.1.5-3",
        "targetState":"present"
      },
      {
        "name":"premium/portainer",
        "version":"2.21.2-1",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "2Gi"
          }
        }
      }
    ],
    "config": {
      "global": {
        "present": {
          "exampleKey": "exampleValue"
        }
      },
      "dogus": {
        "ldap-mapper": {
          "config": {
            "present": {
              "backend/type": "embedded",
              "backend/host": "ldap",
              "backend/port": "389"
            }
          },
          "sensitiveConfig": {
            "present": {
              "exampleKey": "exampleValue"
            }
          }
        }
      }
    },
    "components": [
      {
        "name":"k8s/k8s-backup-operator",
        "targetState":"present",
        "version":"1.1.1"
      },
      {
        "name":"k8s/k8s-backup-operator-crd",
        "targetState":"present",
        "version":"1.1.1"
      },
      {
        "name":"k8s/k8s-blueprint-operator",
        "targetState":"present",
        "version":"2.0.0"
      },
      {
        "name":"k8s/k8s-blueprint-operator-crd",
        "targetState":"present",
        "version":"1.1.0"
      },
      {
        "name":"k8s/k8s-ces-control",
        "targetState":"present",
        "version":"0.11.1"
      },
      {
        "name":"k8s/k8s-component-operator",
        "targetState":"present",
        "version":"1.2.0"
      },
      {
        "name":"k8s/k8s-component-operator-crd",
        "targetState":"present",
        "version":"1.2.0"
      },
      {
        "name":"k8s/k8s-dogu-operator",
        "version":"3.0.0",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-dogu-operator-crd",
        "version":"2.3.0",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-loki",
        "targetState":"present",
        "version":"3.1.1-3"
      },
      {
        "name":"k8s/k8s-minio",
        "version":"2023.9.23-7",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-prometheus",
        "targetState":"present",
        "version":"57.1.1-6"
      },
      {
        "name":"k8s/k8s-promtail",
        "targetState":"present",
        "version":"2.9.1-6"
      },
      {
        "name":"k8s/k8s-service-discovery",
        "targetState":"present",
        "version":"1.1.0"
      },
      {
        "name":"k8s/k8s-snapshot-controller",
        "targetState":"absent",
        "version":"5.0.1-7"
      },
      {
        "name":"k8s/k8s-snapshot-controller-crd",
        "targetState":"absent",
        "version":"5.0.1-7"
      },
      {
        "name":"k8s/k8s-velero",
        "targetState":"present",
        "version":"5.0.2-7"
      }
    ]}
  blueprintMask: |
    {"blueprintMaskApi":"v1"}
  ignoreDoguHealth: false
  ignoreComponentHealth: false
  allowDoguNamespaceSwitch: false