apiVersion: k8s.cloudogu.com/v1
kind: Blueprint
metadata:
  labels:
    app.kubernetes.io/name: blueprint
    app.kubernetes.io/instance: blueprint-sample
    app.kubernetes.io/part-of: k8s-blueprint-operator
    app.kubernetes.io/created-by: k8s-blueprint-operator
  name: blueprint-sample
spec:
  blueprint: |
    {
    "blueprintApi":"v2",
    "dogus":[
      {
        "name":"official/postgresql",
        "version":"14.13-1",
        "targetState":"present"
      }
    ],
    "components": [
      {
        "name":"k8s/k8s-dogu-operator",
        "version":"3.0.1",
        "targetState":"present"
      }
    ]}
  blueprintMask: |
    {"blueprintMaskApi":"v1"}
  ignoreDoguHealth: false
  ignoreComponentHealth: false
  allowDoguNamespaceSwitch: false
