// Code generated by mockery v2.42.1. DO NOT EDIT.

package kubernetes

import mock "github.com/stretchr/testify/mock"

// MockV1Alpha1Interface is an autogenerated mock type for the V1Alpha1Interface type
type MockV1Alpha1Interface struct {
	mock.Mock
}

type MockV1Alpha1Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockV1Alpha1Interface) EXPECT() *MockV1Alpha1Interface_Expecter {
	return &MockV1Alpha1Interface_Expecter{mock: &_m.Mock}
}

// Blueprints provides a mock function with given fields: namespace
func (_m *MockV1Alpha1Interface) Blueprints(namespace string) BlueprintInterface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Blueprints")
	}

	var r0 BlueprintInterface
	if rf, ok := ret.Get(0).(func(string) BlueprintInterface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(BlueprintInterface)
		}
	}

	return r0
}

// MockV1Alpha1Interface_Blueprints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Blueprints'
type MockV1Alpha1Interface_Blueprints_Call struct {
	*mock.Call
}

// Blueprints is a helper method to define mock.On call
//   - namespace string
func (_e *MockV1Alpha1Interface_Expecter) Blueprints(namespace interface{}) *MockV1Alpha1Interface_Blueprints_Call {
	return &MockV1Alpha1Interface_Blueprints_Call{Call: _e.mock.On("Blueprints", namespace)}
}

func (_c *MockV1Alpha1Interface_Blueprints_Call) Run(run func(namespace string)) *MockV1Alpha1Interface_Blueprints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockV1Alpha1Interface_Blueprints_Call) Return(_a0 BlueprintInterface) *MockV1Alpha1Interface_Blueprints_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockV1Alpha1Interface_Blueprints_Call) RunAndReturn(run func(string) BlueprintInterface) *MockV1Alpha1Interface_Blueprints_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockV1Alpha1Interface creates a new instance of MockV1Alpha1Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockV1Alpha1Interface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockV1Alpha1Interface {
	mock := &MockV1Alpha1Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
