apiVersion: k8s.cloudogu.com/v1
kind: Blueprint
metadata:
  labels:
    app.kubernetes.io/name: blueprint
    app.kubernetes.io/instance: blueprint-sample
    app.kubernetes.io/part-of: k8s-blueprint-operator
    app.kubernetes.io/created-by: k8s-blueprint-operator
  name: blueprint-logging-stack-install
spec:
  blueprint: |
    {
    "blueprintApi":"v2",
    "components": [
      {
        "name":"k8s/k8s-minio",
        "version":"2023.9.23-4",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-ces-control",
        "version":"0.3.0",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-loki",
        "version":"2.9.1-4",
        "targetState":"present"
      }
    ]}
  blueprintMask: |
    {"blueprintMaskApi":"v1"}
  ignoreDoguHealth: false
  allowDoguNamespaceSwitch: false
