// Code generated by mockery v2.42.1. DO NOT EDIT.

package domainservice

import (
	context "context"

	config "github.com/cloudogu/k8s-registry-lib/config"

	dogu "github.com/cloudogu/ces-commons-lib/dogu"

	mock "github.com/stretchr/testify/mock"
)

// MockSensitiveDoguConfigRepository is an autogenerated mock type for the SensitiveDoguConfigRepository type
type MockSensitiveDoguConfigRepository struct {
	mock.Mock
}

type MockSensitiveDoguConfigRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSensitiveDoguConfigRepository) EXPECT() *MockSensitiveDoguConfigRepository_Expecter {
	return &MockSensitiveDoguConfigRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockSensitiveDoguConfigRepository) Create(ctx context.Context, _a1 config.DoguConfig) (config.DoguConfig, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 config.DoguConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, config.DoguConfig) (config.DoguConfig, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, config.DoguConfig) config.DoguConfig); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(config.DoguConfig)
	}

	if rf, ok := ret.Get(1).(func(context.Context, config.DoguConfig) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSensitiveDoguConfigRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSensitiveDoguConfigRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 config.DoguConfig
func (_e *MockSensitiveDoguConfigRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *MockSensitiveDoguConfigRepository_Create_Call {
	return &MockSensitiveDoguConfigRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockSensitiveDoguConfigRepository_Create_Call) Run(run func(ctx context.Context, _a1 config.DoguConfig)) *MockSensitiveDoguConfigRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(config.DoguConfig))
	})
	return _c
}

func (_c *MockSensitiveDoguConfigRepository_Create_Call) Return(_a0 config.DoguConfig, _a1 error) *MockSensitiveDoguConfigRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSensitiveDoguConfigRepository_Create_Call) RunAndReturn(run func(context.Context, config.DoguConfig) (config.DoguConfig, error)) *MockSensitiveDoguConfigRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, doguName
func (_m *MockSensitiveDoguConfigRepository) Get(ctx context.Context, doguName dogu.SimpleDoguName) (config.DoguConfig, error) {
	ret := _m.Called(ctx, doguName)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 config.DoguConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dogu.SimpleDoguName) (config.DoguConfig, error)); ok {
		return rf(ctx, doguName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dogu.SimpleDoguName) config.DoguConfig); ok {
		r0 = rf(ctx, doguName)
	} else {
		r0 = ret.Get(0).(config.DoguConfig)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dogu.SimpleDoguName) error); ok {
		r1 = rf(ctx, doguName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSensitiveDoguConfigRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSensitiveDoguConfigRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - doguName dogu.SimpleDoguName
func (_e *MockSensitiveDoguConfigRepository_Expecter) Get(ctx interface{}, doguName interface{}) *MockSensitiveDoguConfigRepository_Get_Call {
	return &MockSensitiveDoguConfigRepository_Get_Call{Call: _e.mock.On("Get", ctx, doguName)}
}

func (_c *MockSensitiveDoguConfigRepository_Get_Call) Run(run func(ctx context.Context, doguName dogu.SimpleDoguName)) *MockSensitiveDoguConfigRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dogu.SimpleDoguName))
	})
	return _c
}

func (_c *MockSensitiveDoguConfigRepository_Get_Call) Return(_a0 config.DoguConfig, _a1 error) *MockSensitiveDoguConfigRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSensitiveDoguConfigRepository_Get_Call) RunAndReturn(run func(context.Context, dogu.SimpleDoguName) (config.DoguConfig, error)) *MockSensitiveDoguConfigRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx, doguNames
func (_m *MockSensitiveDoguConfigRepository) GetAll(ctx context.Context, doguNames []dogu.SimpleDoguName) (map[dogu.SimpleDoguName]config.DoguConfig, error) {
	ret := _m.Called(ctx, doguNames)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[dogu.SimpleDoguName]config.DoguConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []dogu.SimpleDoguName) (map[dogu.SimpleDoguName]config.DoguConfig, error)); ok {
		return rf(ctx, doguNames)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []dogu.SimpleDoguName) map[dogu.SimpleDoguName]config.DoguConfig); ok {
		r0 = rf(ctx, doguNames)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[dogu.SimpleDoguName]config.DoguConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []dogu.SimpleDoguName) error); ok {
		r1 = rf(ctx, doguNames)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSensitiveDoguConfigRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockSensitiveDoguConfigRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - doguNames []dogu.SimpleDoguName
func (_e *MockSensitiveDoguConfigRepository_Expecter) GetAll(ctx interface{}, doguNames interface{}) *MockSensitiveDoguConfigRepository_GetAll_Call {
	return &MockSensitiveDoguConfigRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, doguNames)}
}

func (_c *MockSensitiveDoguConfigRepository_GetAll_Call) Run(run func(ctx context.Context, doguNames []dogu.SimpleDoguName)) *MockSensitiveDoguConfigRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]dogu.SimpleDoguName))
	})
	return _c
}

func (_c *MockSensitiveDoguConfigRepository_GetAll_Call) Return(_a0 map[dogu.SimpleDoguName]config.DoguConfig, _a1 error) *MockSensitiveDoguConfigRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSensitiveDoguConfigRepository_GetAll_Call) RunAndReturn(run func(context.Context, []dogu.SimpleDoguName) (map[dogu.SimpleDoguName]config.DoguConfig, error)) *MockSensitiveDoguConfigRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllExisting provides a mock function with given fields: ctx, doguNames
func (_m *MockSensitiveDoguConfigRepository) GetAllExisting(ctx context.Context, doguNames []dogu.SimpleDoguName) (map[dogu.SimpleDoguName]config.DoguConfig, error) {
	ret := _m.Called(ctx, doguNames)

	if len(ret) == 0 {
		panic("no return value specified for GetAllExisting")
	}

	var r0 map[dogu.SimpleDoguName]config.DoguConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []dogu.SimpleDoguName) (map[dogu.SimpleDoguName]config.DoguConfig, error)); ok {
		return rf(ctx, doguNames)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []dogu.SimpleDoguName) map[dogu.SimpleDoguName]config.DoguConfig); ok {
		r0 = rf(ctx, doguNames)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[dogu.SimpleDoguName]config.DoguConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []dogu.SimpleDoguName) error); ok {
		r1 = rf(ctx, doguNames)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSensitiveDoguConfigRepository_GetAllExisting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllExisting'
type MockSensitiveDoguConfigRepository_GetAllExisting_Call struct {
	*mock.Call
}

// GetAllExisting is a helper method to define mock.On call
//   - ctx context.Context
//   - doguNames []dogu.SimpleDoguName
func (_e *MockSensitiveDoguConfigRepository_Expecter) GetAllExisting(ctx interface{}, doguNames interface{}) *MockSensitiveDoguConfigRepository_GetAllExisting_Call {
	return &MockSensitiveDoguConfigRepository_GetAllExisting_Call{Call: _e.mock.On("GetAllExisting", ctx, doguNames)}
}

func (_c *MockSensitiveDoguConfigRepository_GetAllExisting_Call) Run(run func(ctx context.Context, doguNames []dogu.SimpleDoguName)) *MockSensitiveDoguConfigRepository_GetAllExisting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]dogu.SimpleDoguName))
	})
	return _c
}

func (_c *MockSensitiveDoguConfigRepository_GetAllExisting_Call) Return(_a0 map[dogu.SimpleDoguName]config.DoguConfig, _a1 error) *MockSensitiveDoguConfigRepository_GetAllExisting_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSensitiveDoguConfigRepository_GetAllExisting_Call) RunAndReturn(run func(context.Context, []dogu.SimpleDoguName) (map[dogu.SimpleDoguName]config.DoguConfig, error)) *MockSensitiveDoguConfigRepository_GetAllExisting_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *MockSensitiveDoguConfigRepository) Update(ctx context.Context, _a1 config.DoguConfig) (config.DoguConfig, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 config.DoguConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, config.DoguConfig) (config.DoguConfig, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, config.DoguConfig) config.DoguConfig); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(config.DoguConfig)
	}

	if rf, ok := ret.Get(1).(func(context.Context, config.DoguConfig) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSensitiveDoguConfigRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSensitiveDoguConfigRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 config.DoguConfig
func (_e *MockSensitiveDoguConfigRepository_Expecter) Update(ctx interface{}, _a1 interface{}) *MockSensitiveDoguConfigRepository_Update_Call {
	return &MockSensitiveDoguConfigRepository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *MockSensitiveDoguConfigRepository_Update_Call) Run(run func(ctx context.Context, _a1 config.DoguConfig)) *MockSensitiveDoguConfigRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(config.DoguConfig))
	})
	return _c
}

func (_c *MockSensitiveDoguConfigRepository_Update_Call) Return(_a0 config.DoguConfig, _a1 error) *MockSensitiveDoguConfigRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSensitiveDoguConfigRepository_Update_Call) RunAndReturn(run func(context.Context, config.DoguConfig) (config.DoguConfig, error)) *MockSensitiveDoguConfigRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrCreate provides a mock function with given fields: ctx, _a1
func (_m *MockSensitiveDoguConfigRepository) UpdateOrCreate(ctx context.Context, _a1 config.DoguConfig) (config.DoguConfig, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrCreate")
	}

	var r0 config.DoguConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, config.DoguConfig) (config.DoguConfig, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, config.DoguConfig) config.DoguConfig); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(config.DoguConfig)
	}

	if rf, ok := ret.Get(1).(func(context.Context, config.DoguConfig) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSensitiveDoguConfigRepository_UpdateOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrCreate'
type MockSensitiveDoguConfigRepository_UpdateOrCreate_Call struct {
	*mock.Call
}

// UpdateOrCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 config.DoguConfig
func (_e *MockSensitiveDoguConfigRepository_Expecter) UpdateOrCreate(ctx interface{}, _a1 interface{}) *MockSensitiveDoguConfigRepository_UpdateOrCreate_Call {
	return &MockSensitiveDoguConfigRepository_UpdateOrCreate_Call{Call: _e.mock.On("UpdateOrCreate", ctx, _a1)}
}

func (_c *MockSensitiveDoguConfigRepository_UpdateOrCreate_Call) Run(run func(ctx context.Context, _a1 config.DoguConfig)) *MockSensitiveDoguConfigRepository_UpdateOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(config.DoguConfig))
	})
	return _c
}

func (_c *MockSensitiveDoguConfigRepository_UpdateOrCreate_Call) Return(_a0 config.DoguConfig, _a1 error) *MockSensitiveDoguConfigRepository_UpdateOrCreate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSensitiveDoguConfigRepository_UpdateOrCreate_Call) RunAndReturn(run func(context.Context, config.DoguConfig) (config.DoguConfig, error)) *MockSensitiveDoguConfigRepository_UpdateOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSensitiveDoguConfigRepository creates a new instance of MockSensitiveDoguConfigRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSensitiveDoguConfigRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSensitiveDoguConfigRepository {
	mock := &MockSensitiveDoguConfigRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
