// Code generated by mockery v2.20.0. DO NOT EDIT.

package domainservice

import (
	context "context"

	ecosystem "github.com/cloudogu/k8s-blueprint-operator/pkg/domain/ecosystem"
	mock "github.com/stretchr/testify/mock"
)

// MockDoguInstallationRepository is an autogenerated mock type for the DoguInstallationRepository type
type MockDoguInstallationRepository struct {
	mock.Mock
}

type MockDoguInstallationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoguInstallationRepository) EXPECT() *MockDoguInstallationRepository_Expecter {
	return &MockDoguInstallationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, dogu
func (_m *MockDoguInstallationRepository) Create(ctx context.Context, dogu *ecosystem.DoguInstallation) error {
	ret := _m.Called(ctx, dogu)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ecosystem.DoguInstallation) error); ok {
		r0 = rf(ctx, dogu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDoguInstallationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDoguInstallationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - dogu *ecosystem.DoguInstallation
func (_e *MockDoguInstallationRepository_Expecter) Create(ctx interface{}, dogu interface{}) *MockDoguInstallationRepository_Create_Call {
	return &MockDoguInstallationRepository_Create_Call{Call: _e.mock.On("Create", ctx, dogu)}
}

func (_c *MockDoguInstallationRepository_Create_Call) Run(run func(ctx context.Context, dogu *ecosystem.DoguInstallation)) *MockDoguInstallationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*ecosystem.DoguInstallation))
	})
	return _c
}

func (_c *MockDoguInstallationRepository_Create_Call) Return(_a0 error) *MockDoguInstallationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDoguInstallationRepository_Create_Call) RunAndReturn(run func(context.Context, *ecosystem.DoguInstallation) error) *MockDoguInstallationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, doguName
func (_m *MockDoguInstallationRepository) Delete(ctx context.Context, doguName string) error {
	ret := _m.Called(ctx, doguName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, doguName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDoguInstallationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDoguInstallationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - doguName string
func (_e *MockDoguInstallationRepository_Expecter) Delete(ctx interface{}, doguName interface{}) *MockDoguInstallationRepository_Delete_Call {
	return &MockDoguInstallationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, doguName)}
}

func (_c *MockDoguInstallationRepository_Delete_Call) Run(run func(ctx context.Context, doguName string)) *MockDoguInstallationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDoguInstallationRepository_Delete_Call) Return(_a0 error) *MockDoguInstallationRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDoguInstallationRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockDoguInstallationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockDoguInstallationRepository) GetAll(ctx context.Context) (map[string]*ecosystem.DoguInstallation, error) {
	ret := _m.Called(ctx)

	var r0 map[string]*ecosystem.DoguInstallation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]*ecosystem.DoguInstallation, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]*ecosystem.DoguInstallation); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*ecosystem.DoguInstallation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDoguInstallationRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockDoguInstallationRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDoguInstallationRepository_Expecter) GetAll(ctx interface{}) *MockDoguInstallationRepository_GetAll_Call {
	return &MockDoguInstallationRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockDoguInstallationRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockDoguInstallationRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDoguInstallationRepository_GetAll_Call) Return(_a0 map[string]*ecosystem.DoguInstallation, _a1 error) *MockDoguInstallationRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDoguInstallationRepository_GetAll_Call) RunAndReturn(run func(context.Context) (map[string]*ecosystem.DoguInstallation, error)) *MockDoguInstallationRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, doguName
func (_m *MockDoguInstallationRepository) GetByName(ctx context.Context, doguName string) (*ecosystem.DoguInstallation, error) {
	ret := _m.Called(ctx, doguName)

	var r0 *ecosystem.DoguInstallation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ecosystem.DoguInstallation, error)); ok {
		return rf(ctx, doguName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ecosystem.DoguInstallation); ok {
		r0 = rf(ctx, doguName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ecosystem.DoguInstallation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, doguName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDoguInstallationRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockDoguInstallationRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - doguName string
func (_e *MockDoguInstallationRepository_Expecter) GetByName(ctx interface{}, doguName interface{}) *MockDoguInstallationRepository_GetByName_Call {
	return &MockDoguInstallationRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, doguName)}
}

func (_c *MockDoguInstallationRepository_GetByName_Call) Run(run func(ctx context.Context, doguName string)) *MockDoguInstallationRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDoguInstallationRepository_GetByName_Call) Return(_a0 *ecosystem.DoguInstallation, _a1 error) *MockDoguInstallationRepository_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDoguInstallationRepository_GetByName_Call) RunAndReturn(run func(context.Context, string) (*ecosystem.DoguInstallation, error)) *MockDoguInstallationRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, dogu
func (_m *MockDoguInstallationRepository) Update(ctx context.Context, dogu *ecosystem.DoguInstallation) error {
	ret := _m.Called(ctx, dogu)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ecosystem.DoguInstallation) error); ok {
		r0 = rf(ctx, dogu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDoguInstallationRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDoguInstallationRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - dogu *ecosystem.DoguInstallation
func (_e *MockDoguInstallationRepository_Expecter) Update(ctx interface{}, dogu interface{}) *MockDoguInstallationRepository_Update_Call {
	return &MockDoguInstallationRepository_Update_Call{Call: _e.mock.On("Update", ctx, dogu)}
}

func (_c *MockDoguInstallationRepository_Update_Call) Run(run func(ctx context.Context, dogu *ecosystem.DoguInstallation)) *MockDoguInstallationRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*ecosystem.DoguInstallation))
	})
	return _c
}

func (_c *MockDoguInstallationRepository_Update_Call) Return(_a0 error) *MockDoguInstallationRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDoguInstallationRepository_Update_Call) RunAndReturn(run func(context.Context, *ecosystem.DoguInstallation) error) *MockDoguInstallationRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockDoguInstallationRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockDoguInstallationRepository creates a new instance of MockDoguInstallationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockDoguInstallationRepository(t mockConstructorTestingTNewMockDoguInstallationRepository) *MockDoguInstallationRepository {
	mock := &MockDoguInstallationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
