// Code generated by mockery v2.53.3. DO NOT EDIT.

package domainservice

import (
	context "context"

	ecosystem "github.com/cloudogu/k8s-blueprint-operator/v2/pkg/domain/ecosystem"
	mock "github.com/stretchr/testify/mock"
)

// MockDebugModeRepository is an autogenerated mock type for the DebugModeRepository type
type MockDebugModeRepository struct {
	mock.Mock
}

type MockDebugModeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDebugModeRepository) EXPECT() *MockDebugModeRepository_Expecter {
	return &MockDebugModeRepository_Expecter{mock: &_m.Mock}
}

// GetSingleton provides a mock function with given fields: ctx
func (_m *MockDebugModeRepository) GetSingleton(ctx context.Context) (*ecosystem.DebugMode, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSingleton")
	}

	var r0 *ecosystem.DebugMode
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*ecosystem.DebugMode, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *ecosystem.DebugMode); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ecosystem.DebugMode)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDebugModeRepository_GetSingleton_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSingleton'
type MockDebugModeRepository_GetSingleton_Call struct {
	*mock.Call
}

// GetSingleton is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDebugModeRepository_Expecter) GetSingleton(ctx interface{}) *MockDebugModeRepository_GetSingleton_Call {
	return &MockDebugModeRepository_GetSingleton_Call{Call: _e.mock.On("GetSingleton", ctx)}
}

func (_c *MockDebugModeRepository_GetSingleton_Call) Run(run func(ctx context.Context)) *MockDebugModeRepository_GetSingleton_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDebugModeRepository_GetSingleton_Call) Return(_a0 *ecosystem.DebugMode, _a1 error) *MockDebugModeRepository_GetSingleton_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDebugModeRepository_GetSingleton_Call) RunAndReturn(run func(context.Context) (*ecosystem.DebugMode, error)) *MockDebugModeRepository_GetSingleton_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDebugModeRepository creates a new instance of MockDebugModeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDebugModeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDebugModeRepository {
	mock := &MockDebugModeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
