// Code generated by mockery v2.53.3. DO NOT EDIT.

package application

import (
	context "context"

	domain "github.com/cloudogu/k8s-blueprint-operator/v2/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockValidateAdditionalMountsDomainUseCase is an autogenerated mock type for the validateAdditionalMountsDomainUseCase type
type mockValidateAdditionalMountsDomainUseCase struct {
	mock.Mock
}

type mockValidateAdditionalMountsDomainUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *mockValidateAdditionalMountsDomainUseCase) EXPECT() *mockValidateAdditionalMountsDomainUseCase_Expecter {
	return &mockValidateAdditionalMountsDomainUseCase_Expecter{mock: &_m.Mock}
}

// ValidateAdditionalMounts provides a mock function with given fields: ctx, effectiveBlueprint
func (_m *mockValidateAdditionalMountsDomainUseCase) ValidateAdditionalMounts(ctx context.Context, effectiveBlueprint domain.EffectiveBlueprint) error {
	ret := _m.Called(ctx, effectiveBlueprint)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAdditionalMounts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.EffectiveBlueprint) error); ok {
		r0 = rf(ctx, effectiveBlueprint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockValidateAdditionalMountsDomainUseCase_ValidateAdditionalMounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAdditionalMounts'
type mockValidateAdditionalMountsDomainUseCase_ValidateAdditionalMounts_Call struct {
	*mock.Call
}

// ValidateAdditionalMounts is a helper method to define mock.On call
//   - ctx context.Context
//   - effectiveBlueprint domain.EffectiveBlueprint
func (_e *mockValidateAdditionalMountsDomainUseCase_Expecter) ValidateAdditionalMounts(ctx interface{}, effectiveBlueprint interface{}) *mockValidateAdditionalMountsDomainUseCase_ValidateAdditionalMounts_Call {
	return &mockValidateAdditionalMountsDomainUseCase_ValidateAdditionalMounts_Call{Call: _e.mock.On("ValidateAdditionalMounts", ctx, effectiveBlueprint)}
}

func (_c *mockValidateAdditionalMountsDomainUseCase_ValidateAdditionalMounts_Call) Run(run func(ctx context.Context, effectiveBlueprint domain.EffectiveBlueprint)) *mockValidateAdditionalMountsDomainUseCase_ValidateAdditionalMounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.EffectiveBlueprint))
	})
	return _c
}

func (_c *mockValidateAdditionalMountsDomainUseCase_ValidateAdditionalMounts_Call) Return(_a0 error) *mockValidateAdditionalMountsDomainUseCase_ValidateAdditionalMounts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockValidateAdditionalMountsDomainUseCase_ValidateAdditionalMounts_Call) RunAndReturn(run func(context.Context, domain.EffectiveBlueprint) error) *mockValidateAdditionalMountsDomainUseCase_ValidateAdditionalMounts_Call {
	_c.Call.Return(run)
	return _c
}

// newMockValidateAdditionalMountsDomainUseCase creates a new instance of mockValidateAdditionalMountsDomainUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockValidateAdditionalMountsDomainUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockValidateAdditionalMountsDomainUseCase {
	mock := &mockValidateAdditionalMountsDomainUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
