// Code generated by mockery v2.53.3. DO NOT EDIT.

package application

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockRestoreRepository is an autogenerated mock type for the restoreRepository type
type mockRestoreRepository struct {
	mock.Mock
}

type mockRestoreRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRestoreRepository) EXPECT() *mockRestoreRepository_Expecter {
	return &mockRestoreRepository_Expecter{mock: &_m.Mock}
}

// IsRestoreInProgress provides a mock function with given fields: ctx
func (_m *mockRestoreRepository) IsRestoreInProgress(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsRestoreInProgress")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRestoreRepository_IsRestoreInProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRestoreInProgress'
type mockRestoreRepository_IsRestoreInProgress_Call struct {
	*mock.Call
}

// IsRestoreInProgress is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockRestoreRepository_Expecter) IsRestoreInProgress(ctx interface{}) *mockRestoreRepository_IsRestoreInProgress_Call {
	return &mockRestoreRepository_IsRestoreInProgress_Call{Call: _e.mock.On("IsRestoreInProgress", ctx)}
}

func (_c *mockRestoreRepository_IsRestoreInProgress_Call) Run(run func(ctx context.Context)) *mockRestoreRepository_IsRestoreInProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockRestoreRepository_IsRestoreInProgress_Call) Return(_a0 bool, _a1 error) *mockRestoreRepository_IsRestoreInProgress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRestoreRepository_IsRestoreInProgress_Call) RunAndReturn(run func(context.Context) (bool, error)) *mockRestoreRepository_IsRestoreInProgress_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRestoreRepository creates a new instance of mockRestoreRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRestoreRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRestoreRepository {
	mock := &mockRestoreRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
