// Code generated by mockery v2.20.0. DO NOT EDIT.

package application

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockComponentInstallationUseCase is an autogenerated mock type for the componentInstallationUseCase type
type mockComponentInstallationUseCase struct {
	mock.Mock
}

type mockComponentInstallationUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *mockComponentInstallationUseCase) EXPECT() *mockComponentInstallationUseCase_Expecter {
	return &mockComponentInstallationUseCase_Expecter{mock: &_m.Mock}
}

// ApplyComponentStates provides a mock function with given fields: ctx, blueprintId
func (_m *mockComponentInstallationUseCase) ApplyComponentStates(ctx context.Context, blueprintId string) error {
	ret := _m.Called(ctx, blueprintId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, blueprintId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockComponentInstallationUseCase_ApplyComponentStates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyComponentStates'
type mockComponentInstallationUseCase_ApplyComponentStates_Call struct {
	*mock.Call
}

// ApplyComponentStates is a helper method to define mock.On call
//   - ctx context.Context
//   - blueprintId string
func (_e *mockComponentInstallationUseCase_Expecter) ApplyComponentStates(ctx interface{}, blueprintId interface{}) *mockComponentInstallationUseCase_ApplyComponentStates_Call {
	return &mockComponentInstallationUseCase_ApplyComponentStates_Call{Call: _e.mock.On("ApplyComponentStates", ctx, blueprintId)}
}

func (_c *mockComponentInstallationUseCase_ApplyComponentStates_Call) Run(run func(ctx context.Context, blueprintId string)) *mockComponentInstallationUseCase_ApplyComponentStates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockComponentInstallationUseCase_ApplyComponentStates_Call) Return(_a0 error) *mockComponentInstallationUseCase_ApplyComponentStates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockComponentInstallationUseCase_ApplyComponentStates_Call) RunAndReturn(run func(context.Context, string) error) *mockComponentInstallationUseCase_ApplyComponentStates_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockComponentInstallationUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// newMockComponentInstallationUseCase creates a new instance of mockComponentInstallationUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockComponentInstallationUseCase(t mockConstructorTestingTnewMockComponentInstallationUseCase) *mockComponentInstallationUseCase {
	mock := &mockComponentInstallationUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
