// Code generated by mockery v2.20.0. DO NOT EDIT.

package application

import (
	context "context"

	domain "github.com/cloudogu/k8s-blueprint-operator/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockHealthConfigRepository is an autogenerated mock type for the healthConfigRepository type
type mockHealthConfigRepository struct {
	mock.Mock
}

type mockHealthConfigRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockHealthConfigRepository) EXPECT() *mockHealthConfigRepository_Expecter {
	return &mockHealthConfigRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx
func (_m *mockHealthConfigRepository) Get(ctx context.Context) (domain.HealthConfig, error) {
	ret := _m.Called(ctx)

	var r0 domain.HealthConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (domain.HealthConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) domain.HealthConfig); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(domain.HealthConfig)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockHealthConfigRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockHealthConfigRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockHealthConfigRepository_Expecter) Get(ctx interface{}) *mockHealthConfigRepository_Get_Call {
	return &mockHealthConfigRepository_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *mockHealthConfigRepository_Get_Call) Run(run func(ctx context.Context)) *mockHealthConfigRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockHealthConfigRepository_Get_Call) Return(_a0 domain.HealthConfig, _a1 error) *mockHealthConfigRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockHealthConfigRepository_Get_Call) RunAndReturn(run func(context.Context) (domain.HealthConfig, error)) *mockHealthConfigRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockHealthConfigRepository interface {
	mock.TestingT
	Cleanup(func())
}

// newMockHealthConfigRepository creates a new instance of mockHealthConfigRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockHealthConfigRepository(t mockConstructorTestingTnewMockHealthConfigRepository) *mockHealthConfigRepository {
	mock := &mockHealthConfigRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
