// Code generated by mockery v2.20.0. DO NOT EDIT.

package application

import (
	context "context"

	common "github.com/cloudogu/k8s-blueprint-operator/pkg/domain/common"

	ecosystem "github.com/cloudogu/k8s-blueprint-operator/pkg/domain/ecosystem"

	mock "github.com/stretchr/testify/mock"
)

// MockGlobalConfigEntryRepository is an autogenerated mock type for the GlobalConfigEntryRepository type
type MockGlobalConfigEntryRepository struct {
	mock.Mock
}

type MockGlobalConfigEntryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGlobalConfigEntryRepository) EXPECT() *MockGlobalConfigEntryRepository_Expecter {
	return &MockGlobalConfigEntryRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, key
func (_m *MockGlobalConfigEntryRepository) Delete(ctx context.Context, key common.SimpleDoguName) error {
	ret := _m.Called(ctx, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, common.SimpleDoguName) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGlobalConfigEntryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockGlobalConfigEntryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key common.SimpleDoguName
func (_e *MockGlobalConfigEntryRepository_Expecter) Delete(ctx interface{}, key interface{}) *MockGlobalConfigEntryRepository_Delete_Call {
	return &MockGlobalConfigEntryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockGlobalConfigEntryRepository_Delete_Call) Run(run func(ctx context.Context, key common.SimpleDoguName)) *MockGlobalConfigEntryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.SimpleDoguName))
	})
	return _c
}

func (_c *MockGlobalConfigEntryRepository_Delete_Call) Return(_a0 error) *MockGlobalConfigEntryRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGlobalConfigEntryRepository_Delete_Call) RunAndReturn(run func(context.Context, common.SimpleDoguName) error) *MockGlobalConfigEntryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockGlobalConfigEntryRepository) GetAll(ctx context.Context) ([]*ecosystem.GlobalConfigEntry, error) {
	ret := _m.Called(ctx)

	var r0 []*ecosystem.GlobalConfigEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*ecosystem.GlobalConfigEntry, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*ecosystem.GlobalConfigEntry); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ecosystem.GlobalConfigEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGlobalConfigEntryRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockGlobalConfigEntryRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGlobalConfigEntryRepository_Expecter) GetAll(ctx interface{}) *MockGlobalConfigEntryRepository_GetAll_Call {
	return &MockGlobalConfigEntryRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockGlobalConfigEntryRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockGlobalConfigEntryRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockGlobalConfigEntryRepository_GetAll_Call) Return(_a0 []*ecosystem.GlobalConfigEntry, _a1 error) *MockGlobalConfigEntryRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGlobalConfigEntryRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]*ecosystem.GlobalConfigEntry, error)) *MockGlobalConfigEntryRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: _a0, _a1
func (_m *MockGlobalConfigEntryRepository) Save(_a0 context.Context, _a1 *ecosystem.GlobalConfigEntry) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ecosystem.GlobalConfigEntry) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGlobalConfigEntryRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockGlobalConfigEntryRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *ecosystem.GlobalConfigEntry
func (_e *MockGlobalConfigEntryRepository_Expecter) Save(_a0 interface{}, _a1 interface{}) *MockGlobalConfigEntryRepository_Save_Call {
	return &MockGlobalConfigEntryRepository_Save_Call{Call: _e.mock.On("Save", _a0, _a1)}
}

func (_c *MockGlobalConfigEntryRepository_Save_Call) Run(run func(_a0 context.Context, _a1 *ecosystem.GlobalConfigEntry)) *MockGlobalConfigEntryRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*ecosystem.GlobalConfigEntry))
	})
	return _c
}

func (_c *MockGlobalConfigEntryRepository_Save_Call) Return(_a0 error) *MockGlobalConfigEntryRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGlobalConfigEntryRepository_Save_Call) RunAndReturn(run func(context.Context, *ecosystem.GlobalConfigEntry) error) *MockGlobalConfigEntryRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAll provides a mock function with given fields: ctx, keys
func (_m *MockGlobalConfigEntryRepository) SaveAll(ctx context.Context, keys []*ecosystem.GlobalConfigEntry) error {
	ret := _m.Called(ctx, keys)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*ecosystem.GlobalConfigEntry) error); ok {
		r0 = rf(ctx, keys)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGlobalConfigEntryRepository_SaveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAll'
type MockGlobalConfigEntryRepository_SaveAll_Call struct {
	*mock.Call
}

// SaveAll is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []*ecosystem.GlobalConfigEntry
func (_e *MockGlobalConfigEntryRepository_Expecter) SaveAll(ctx interface{}, keys interface{}) *MockGlobalConfigEntryRepository_SaveAll_Call {
	return &MockGlobalConfigEntryRepository_SaveAll_Call{Call: _e.mock.On("SaveAll", ctx, keys)}
}

func (_c *MockGlobalConfigEntryRepository_SaveAll_Call) Run(run func(ctx context.Context, keys []*ecosystem.GlobalConfigEntry)) *MockGlobalConfigEntryRepository_SaveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*ecosystem.GlobalConfigEntry))
	})
	return _c
}

func (_c *MockGlobalConfigEntryRepository_SaveAll_Call) Return(_a0 error) *MockGlobalConfigEntryRepository_SaveAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGlobalConfigEntryRepository_SaveAll_Call) RunAndReturn(run func(context.Context, []*ecosystem.GlobalConfigEntry) error) *MockGlobalConfigEntryRepository_SaveAll_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockGlobalConfigEntryRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockGlobalConfigEntryRepository creates a new instance of MockGlobalConfigEntryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockGlobalConfigEntryRepository(t mockConstructorTestingTNewMockGlobalConfigEntryRepository) *MockGlobalConfigEntryRepository {
	mock := &MockGlobalConfigEntryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
