// Code generated by mockery v2.20.0. DO NOT EDIT.

package application

import (
	context "context"

	common "github.com/cloudogu/k8s-blueprint-operator/pkg/domain/common"

	ecosystem "github.com/cloudogu/k8s-blueprint-operator/pkg/domain/ecosystem"

	mock "github.com/stretchr/testify/mock"
)

// mockDoguConfigRepository is an autogenerated mock type for the doguConfigRepository type
type mockDoguConfigRepository struct {
	mock.Mock
}

type mockDoguConfigRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguConfigRepository) EXPECT() *mockDoguConfigRepository_Expecter {
	return &mockDoguConfigRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *mockDoguConfigRepository) Delete(_a0 context.Context, _a1 common.DoguConfigKey) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, common.DoguConfigKey) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguConfigRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockDoguConfigRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 common.DoguConfigKey
func (_e *mockDoguConfigRepository_Expecter) Delete(_a0 interface{}, _a1 interface{}) *mockDoguConfigRepository_Delete_Call {
	return &mockDoguConfigRepository_Delete_Call{Call: _e.mock.On("Delete", _a0, _a1)}
}

func (_c *mockDoguConfigRepository_Delete_Call) Run(run func(_a0 context.Context, _a1 common.DoguConfigKey)) *mockDoguConfigRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.DoguConfigKey))
	})
	return _c
}

func (_c *mockDoguConfigRepository_Delete_Call) Return(_a0 error) *mockDoguConfigRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguConfigRepository_Delete_Call) RunAndReturn(run func(context.Context, common.DoguConfigKey) error) *mockDoguConfigRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllByKeys provides a mock function with given fields: _a0, _a1
func (_m *mockDoguConfigRepository) DeleteAllByKeys(_a0 context.Context, _a1 []common.DoguConfigKey) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []common.DoguConfigKey) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguConfigRepository_DeleteAllByKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllByKeys'
type mockDoguConfigRepository_DeleteAllByKeys_Call struct {
	*mock.Call
}

// DeleteAllByKeys is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []common.DoguConfigKey
func (_e *mockDoguConfigRepository_Expecter) DeleteAllByKeys(_a0 interface{}, _a1 interface{}) *mockDoguConfigRepository_DeleteAllByKeys_Call {
	return &mockDoguConfigRepository_DeleteAllByKeys_Call{Call: _e.mock.On("DeleteAllByKeys", _a0, _a1)}
}

func (_c *mockDoguConfigRepository_DeleteAllByKeys_Call) Run(run func(_a0 context.Context, _a1 []common.DoguConfigKey)) *mockDoguConfigRepository_DeleteAllByKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]common.DoguConfigKey))
	})
	return _c
}

func (_c *mockDoguConfigRepository_DeleteAllByKeys_Call) Return(_a0 error) *mockDoguConfigRepository_DeleteAllByKeys_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguConfigRepository_DeleteAllByKeys_Call) RunAndReturn(run func(context.Context, []common.DoguConfigKey) error) *mockDoguConfigRepository_DeleteAllByKeys_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *mockDoguConfigRepository) Get(_a0 context.Context, _a1 common.DoguConfigKey) (*ecosystem.DoguConfigEntry, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *ecosystem.DoguConfigEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.DoguConfigKey) (*ecosystem.DoguConfigEntry, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.DoguConfigKey) *ecosystem.DoguConfigEntry); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ecosystem.DoguConfigEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.DoguConfigKey) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDoguConfigRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockDoguConfigRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 common.DoguConfigKey
func (_e *mockDoguConfigRepository_Expecter) Get(_a0 interface{}, _a1 interface{}) *mockDoguConfigRepository_Get_Call {
	return &mockDoguConfigRepository_Get_Call{Call: _e.mock.On("Get", _a0, _a1)}
}

func (_c *mockDoguConfigRepository_Get_Call) Run(run func(_a0 context.Context, _a1 common.DoguConfigKey)) *mockDoguConfigRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.DoguConfigKey))
	})
	return _c
}

func (_c *mockDoguConfigRepository_Get_Call) Return(_a0 *ecosystem.DoguConfigEntry, _a1 error) *mockDoguConfigRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDoguConfigRepository_Get_Call) RunAndReturn(run func(context.Context, common.DoguConfigKey) (*ecosystem.DoguConfigEntry, error)) *mockDoguConfigRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByKey provides a mock function with given fields: _a0, _a1
func (_m *mockDoguConfigRepository) GetAllByKey(_a0 context.Context, _a1 []common.DoguConfigKey) (map[common.DoguConfigKey]*ecosystem.DoguConfigEntry, error) {
	ret := _m.Called(_a0, _a1)

	var r0 map[common.DoguConfigKey]*ecosystem.DoguConfigEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []common.DoguConfigKey) (map[common.DoguConfigKey]*ecosystem.DoguConfigEntry, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []common.DoguConfigKey) map[common.DoguConfigKey]*ecosystem.DoguConfigEntry); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[common.DoguConfigKey]*ecosystem.DoguConfigEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []common.DoguConfigKey) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDoguConfigRepository_GetAllByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByKey'
type mockDoguConfigRepository_GetAllByKey_Call struct {
	*mock.Call
}

// GetAllByKey is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []common.DoguConfigKey
func (_e *mockDoguConfigRepository_Expecter) GetAllByKey(_a0 interface{}, _a1 interface{}) *mockDoguConfigRepository_GetAllByKey_Call {
	return &mockDoguConfigRepository_GetAllByKey_Call{Call: _e.mock.On("GetAllByKey", _a0, _a1)}
}

func (_c *mockDoguConfigRepository_GetAllByKey_Call) Run(run func(_a0 context.Context, _a1 []common.DoguConfigKey)) *mockDoguConfigRepository_GetAllByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]common.DoguConfigKey))
	})
	return _c
}

func (_c *mockDoguConfigRepository_GetAllByKey_Call) Return(_a0 map[common.DoguConfigKey]*ecosystem.DoguConfigEntry, _a1 error) *mockDoguConfigRepository_GetAllByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDoguConfigRepository_GetAllByKey_Call) RunAndReturn(run func(context.Context, []common.DoguConfigKey) (map[common.DoguConfigKey]*ecosystem.DoguConfigEntry, error)) *mockDoguConfigRepository_GetAllByKey_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: _a0, _a1
func (_m *mockDoguConfigRepository) Save(_a0 context.Context, _a1 *ecosystem.DoguConfigEntry) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ecosystem.DoguConfigEntry) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguConfigRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type mockDoguConfigRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *ecosystem.DoguConfigEntry
func (_e *mockDoguConfigRepository_Expecter) Save(_a0 interface{}, _a1 interface{}) *mockDoguConfigRepository_Save_Call {
	return &mockDoguConfigRepository_Save_Call{Call: _e.mock.On("Save", _a0, _a1)}
}

func (_c *mockDoguConfigRepository_Save_Call) Run(run func(_a0 context.Context, _a1 *ecosystem.DoguConfigEntry)) *mockDoguConfigRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*ecosystem.DoguConfigEntry))
	})
	return _c
}

func (_c *mockDoguConfigRepository_Save_Call) Return(_a0 error) *mockDoguConfigRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguConfigRepository_Save_Call) RunAndReturn(run func(context.Context, *ecosystem.DoguConfigEntry) error) *mockDoguConfigRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAll provides a mock function with given fields: _a0, _a1
func (_m *mockDoguConfigRepository) SaveAll(_a0 context.Context, _a1 []*ecosystem.DoguConfigEntry) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*ecosystem.DoguConfigEntry) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguConfigRepository_SaveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAll'
type mockDoguConfigRepository_SaveAll_Call struct {
	*mock.Call
}

// SaveAll is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []*ecosystem.DoguConfigEntry
func (_e *mockDoguConfigRepository_Expecter) SaveAll(_a0 interface{}, _a1 interface{}) *mockDoguConfigRepository_SaveAll_Call {
	return &mockDoguConfigRepository_SaveAll_Call{Call: _e.mock.On("SaveAll", _a0, _a1)}
}

func (_c *mockDoguConfigRepository_SaveAll_Call) Run(run func(_a0 context.Context, _a1 []*ecosystem.DoguConfigEntry)) *mockDoguConfigRepository_SaveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*ecosystem.DoguConfigEntry))
	})
	return _c
}

func (_c *mockDoguConfigRepository_SaveAll_Call) Return(_a0 error) *mockDoguConfigRepository_SaveAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguConfigRepository_SaveAll_Call) RunAndReturn(run func(context.Context, []*ecosystem.DoguConfigEntry) error) *mockDoguConfigRepository_SaveAll_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockDoguConfigRepository interface {
	mock.TestingT
	Cleanup(func())
}

// newMockDoguConfigRepository creates a new instance of mockDoguConfigRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockDoguConfigRepository(t mockConstructorTestingTnewMockDoguConfigRepository) *mockDoguConfigRepository {
	mock := &mockDoguConfigRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
