// Code generated by mockery v2.42.1. DO NOT EDIT.

package application

import (
	core "github.com/cloudogu/cesapp-lib/core"
	common "github.com/cloudogu/k8s-blueprint-operator/pkg/domain/common"

	domainservice "github.com/cloudogu/k8s-blueprint-operator/pkg/domainservice"

	mock "github.com/stretchr/testify/mock"
)

// mockRemoteDoguRegistry is an autogenerated mock type for the remoteDoguRegistry type
type mockRemoteDoguRegistry struct {
	mock.Mock
}

type mockRemoteDoguRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRemoteDoguRegistry) EXPECT() *mockRemoteDoguRegistry_Expecter {
	return &mockRemoteDoguRegistry_Expecter{mock: &_m.Mock}
}

// GetDogu provides a mock function with given fields: doguName, version
func (_m *mockRemoteDoguRegistry) GetDogu(doguName common.QualifiedDoguName, version string) (*core.Dogu, error) {
	ret := _m.Called(doguName, version)

	if len(ret) == 0 {
		panic("no return value specified for GetDogu")
	}

	var r0 *core.Dogu
	var r1 error
	if rf, ok := ret.Get(0).(func(common.QualifiedDoguName, string) (*core.Dogu, error)); ok {
		return rf(doguName, version)
	}
	if rf, ok := ret.Get(0).(func(common.QualifiedDoguName, string) *core.Dogu); ok {
		r0 = rf(doguName, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Dogu)
		}
	}

	if rf, ok := ret.Get(1).(func(common.QualifiedDoguName, string) error); ok {
		r1 = rf(doguName, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRemoteDoguRegistry_GetDogu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDogu'
type mockRemoteDoguRegistry_GetDogu_Call struct {
	*mock.Call
}

// GetDogu is a helper method to define mock.On call
//   - doguName common.QualifiedDoguName
//   - version string
func (_e *mockRemoteDoguRegistry_Expecter) GetDogu(doguName interface{}, version interface{}) *mockRemoteDoguRegistry_GetDogu_Call {
	return &mockRemoteDoguRegistry_GetDogu_Call{Call: _e.mock.On("GetDogu", doguName, version)}
}

func (_c *mockRemoteDoguRegistry_GetDogu_Call) Run(run func(doguName common.QualifiedDoguName, version string)) *mockRemoteDoguRegistry_GetDogu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(common.QualifiedDoguName), args[1].(string))
	})
	return _c
}

func (_c *mockRemoteDoguRegistry_GetDogu_Call) Return(_a0 *core.Dogu, _a1 error) *mockRemoteDoguRegistry_GetDogu_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRemoteDoguRegistry_GetDogu_Call) RunAndReturn(run func(common.QualifiedDoguName, string) (*core.Dogu, error)) *mockRemoteDoguRegistry_GetDogu_Call {
	_c.Call.Return(run)
	return _c
}

// GetDogus provides a mock function with given fields: dogusToLoad
func (_m *mockRemoteDoguRegistry) GetDogus(dogusToLoad []domainservice.DoguToLoad) (map[common.QualifiedDoguName]*core.Dogu, error) {
	ret := _m.Called(dogusToLoad)

	if len(ret) == 0 {
		panic("no return value specified for GetDogus")
	}

	var r0 map[common.QualifiedDoguName]*core.Dogu
	var r1 error
	if rf, ok := ret.Get(0).(func([]domainservice.DoguToLoad) (map[common.QualifiedDoguName]*core.Dogu, error)); ok {
		return rf(dogusToLoad)
	}
	if rf, ok := ret.Get(0).(func([]domainservice.DoguToLoad) map[common.QualifiedDoguName]*core.Dogu); ok {
		r0 = rf(dogusToLoad)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[common.QualifiedDoguName]*core.Dogu)
		}
	}

	if rf, ok := ret.Get(1).(func([]domainservice.DoguToLoad) error); ok {
		r1 = rf(dogusToLoad)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRemoteDoguRegistry_GetDogus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDogus'
type mockRemoteDoguRegistry_GetDogus_Call struct {
	*mock.Call
}

// GetDogus is a helper method to define mock.On call
//   - dogusToLoad []domainservice.DoguToLoad
func (_e *mockRemoteDoguRegistry_Expecter) GetDogus(dogusToLoad interface{}) *mockRemoteDoguRegistry_GetDogus_Call {
	return &mockRemoteDoguRegistry_GetDogus_Call{Call: _e.mock.On("GetDogus", dogusToLoad)}
}

func (_c *mockRemoteDoguRegistry_GetDogus_Call) Run(run func(dogusToLoad []domainservice.DoguToLoad)) *mockRemoteDoguRegistry_GetDogus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]domainservice.DoguToLoad))
	})
	return _c
}

func (_c *mockRemoteDoguRegistry_GetDogus_Call) Return(_a0 map[common.QualifiedDoguName]*core.Dogu, _a1 error) *mockRemoteDoguRegistry_GetDogus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRemoteDoguRegistry_GetDogus_Call) RunAndReturn(run func([]domainservice.DoguToLoad) (map[common.QualifiedDoguName]*core.Dogu, error)) *mockRemoteDoguRegistry_GetDogus_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRemoteDoguRegistry creates a new instance of mockRemoteDoguRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRemoteDoguRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRemoteDoguRegistry {
	mock := &mockRemoteDoguRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
