// Code generated by mockery v2.53.3. DO NOT EDIT.

package application

import (
	context "context"

	domain "github.com/cloudogu/k8s-blueprint-operator/v2/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockApplyBlueprintSpecUseCase is an autogenerated mock type for the applyBlueprintSpecUseCase type
type mockApplyBlueprintSpecUseCase struct {
	mock.Mock
}

type mockApplyBlueprintSpecUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *mockApplyBlueprintSpecUseCase) EXPECT() *mockApplyBlueprintSpecUseCase_Expecter {
	return &mockApplyBlueprintSpecUseCase_Expecter{mock: &_m.Mock}
}

// PostProcessBlueprintApplication provides a mock function with given fields: ctx, blueprint
func (_m *mockApplyBlueprintSpecUseCase) PostProcessBlueprintApplication(ctx context.Context, blueprint *domain.BlueprintSpec) error {
	ret := _m.Called(ctx, blueprint)

	if len(ret) == 0 {
		panic("no return value specified for PostProcessBlueprintApplication")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BlueprintSpec) error); ok {
		r0 = rf(ctx, blueprint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockApplyBlueprintSpecUseCase_PostProcessBlueprintApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostProcessBlueprintApplication'
type mockApplyBlueprintSpecUseCase_PostProcessBlueprintApplication_Call struct {
	*mock.Call
}

// PostProcessBlueprintApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - blueprint *domain.BlueprintSpec
func (_e *mockApplyBlueprintSpecUseCase_Expecter) PostProcessBlueprintApplication(ctx interface{}, blueprint interface{}) *mockApplyBlueprintSpecUseCase_PostProcessBlueprintApplication_Call {
	return &mockApplyBlueprintSpecUseCase_PostProcessBlueprintApplication_Call{Call: _e.mock.On("PostProcessBlueprintApplication", ctx, blueprint)}
}

func (_c *mockApplyBlueprintSpecUseCase_PostProcessBlueprintApplication_Call) Run(run func(ctx context.Context, blueprint *domain.BlueprintSpec)) *mockApplyBlueprintSpecUseCase_PostProcessBlueprintApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.BlueprintSpec))
	})
	return _c
}

func (_c *mockApplyBlueprintSpecUseCase_PostProcessBlueprintApplication_Call) Return(_a0 error) *mockApplyBlueprintSpecUseCase_PostProcessBlueprintApplication_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockApplyBlueprintSpecUseCase_PostProcessBlueprintApplication_Call) RunAndReturn(run func(context.Context, *domain.BlueprintSpec) error) *mockApplyBlueprintSpecUseCase_PostProcessBlueprintApplication_Call {
	_c.Call.Return(run)
	return _c
}

// newMockApplyBlueprintSpecUseCase creates a new instance of mockApplyBlueprintSpecUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockApplyBlueprintSpecUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockApplyBlueprintSpecUseCase {
	mock := &mockApplyBlueprintSpecUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
