// Code generated by mockery v2.53.3. DO NOT EDIT.

package application

import (
	context "context"

	domain "github.com/cloudogu/k8s-blueprint-operator/v2/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockInitialBlueprintStatusUseCase is an autogenerated mock type for the initialBlueprintStatusUseCase type
type mockInitialBlueprintStatusUseCase struct {
	mock.Mock
}

type mockInitialBlueprintStatusUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *mockInitialBlueprintStatusUseCase) EXPECT() *mockInitialBlueprintStatusUseCase_Expecter {
	return &mockInitialBlueprintStatusUseCase_Expecter{mock: &_m.Mock}
}

// InitateConditions provides a mock function with given fields: ctx, blueprint
func (_m *mockInitialBlueprintStatusUseCase) InitateConditions(ctx context.Context, blueprint *domain.BlueprintSpec) error {
	ret := _m.Called(ctx, blueprint)

	if len(ret) == 0 {
		panic("no return value specified for InitateConditions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BlueprintSpec) error); ok {
		r0 = rf(ctx, blueprint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockInitialBlueprintStatusUseCase_InitateConditions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitateConditions'
type mockInitialBlueprintStatusUseCase_InitateConditions_Call struct {
	*mock.Call
}

// InitateConditions is a helper method to define mock.On call
//   - ctx context.Context
//   - blueprint *domain.BlueprintSpec
func (_e *mockInitialBlueprintStatusUseCase_Expecter) InitateConditions(ctx interface{}, blueprint interface{}) *mockInitialBlueprintStatusUseCase_InitateConditions_Call {
	return &mockInitialBlueprintStatusUseCase_InitateConditions_Call{Call: _e.mock.On("InitateConditions", ctx, blueprint)}
}

func (_c *mockInitialBlueprintStatusUseCase_InitateConditions_Call) Run(run func(ctx context.Context, blueprint *domain.BlueprintSpec)) *mockInitialBlueprintStatusUseCase_InitateConditions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.BlueprintSpec))
	})
	return _c
}

func (_c *mockInitialBlueprintStatusUseCase_InitateConditions_Call) Return(_a0 error) *mockInitialBlueprintStatusUseCase_InitateConditions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockInitialBlueprintStatusUseCase_InitateConditions_Call) RunAndReturn(run func(context.Context, *domain.BlueprintSpec) error) *mockInitialBlueprintStatusUseCase_InitateConditions_Call {
	_c.Call.Return(run)
	return _c
}

// newMockInitialBlueprintStatusUseCase creates a new instance of mockInitialBlueprintStatusUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockInitialBlueprintStatusUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockInitialBlueprintStatusUseCase {
	mock := &mockInitialBlueprintStatusUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
