// Code generated by mockery v2.53.3. DO NOT EDIT.

package application

import (
	context "context"

	domain "github.com/cloudogu/k8s-blueprint-operator/v2/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockApplyDogusUseCase is an autogenerated mock type for the applyDogusUseCase type
type mockApplyDogusUseCase struct {
	mock.Mock
}

type mockApplyDogusUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *mockApplyDogusUseCase) EXPECT() *mockApplyDogusUseCase_Expecter {
	return &mockApplyDogusUseCase_Expecter{mock: &_m.Mock}
}

// ApplyDogus provides a mock function with given fields: ctx, blueprint
func (_m *mockApplyDogusUseCase) ApplyDogus(ctx context.Context, blueprint *domain.BlueprintSpec) error {
	ret := _m.Called(ctx, blueprint)

	if len(ret) == 0 {
		panic("no return value specified for ApplyDogus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BlueprintSpec) error); ok {
		r0 = rf(ctx, blueprint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockApplyDogusUseCase_ApplyDogus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyDogus'
type mockApplyDogusUseCase_ApplyDogus_Call struct {
	*mock.Call
}

// ApplyDogus is a helper method to define mock.On call
//   - ctx context.Context
//   - blueprint *domain.BlueprintSpec
func (_e *mockApplyDogusUseCase_Expecter) ApplyDogus(ctx interface{}, blueprint interface{}) *mockApplyDogusUseCase_ApplyDogus_Call {
	return &mockApplyDogusUseCase_ApplyDogus_Call{Call: _e.mock.On("ApplyDogus", ctx, blueprint)}
}

func (_c *mockApplyDogusUseCase_ApplyDogus_Call) Run(run func(ctx context.Context, blueprint *domain.BlueprintSpec)) *mockApplyDogusUseCase_ApplyDogus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.BlueprintSpec))
	})
	return _c
}

func (_c *mockApplyDogusUseCase_ApplyDogus_Call) Return(_a0 error) *mockApplyDogusUseCase_ApplyDogus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockApplyDogusUseCase_ApplyDogus_Call) RunAndReturn(run func(context.Context, *domain.BlueprintSpec) error) *mockApplyDogusUseCase_ApplyDogus_Call {
	_c.Call.Return(run)
	return _c
}

// newMockApplyDogusUseCase creates a new instance of mockApplyDogusUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockApplyDogusUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockApplyDogusUseCase {
	mock := &mockApplyDogusUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
