//go:build !ignore_autogenerated

/*
This file was generated with "make generate".
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"github.com/cloudogu/k8s-blueprint-operator/pkg/adapter/serializer"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Blueprint) DeepCopyInto(out *Blueprint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Blueprint.
func (in *Blueprint) DeepCopy() *Blueprint {
	if in == nil {
		return nil
	}
	out := new(Blueprint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Blueprint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueprintList) DeepCopyInto(out *BlueprintList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Blueprint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueprintList.
func (in *BlueprintList) DeepCopy() *BlueprintList {
	if in == nil {
		return nil
	}
	out := new(BlueprintList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlueprintList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueprintSpec) DeepCopyInto(out *BlueprintSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueprintSpec.
func (in *BlueprintSpec) DeepCopy() *BlueprintSpec {
	if in == nil {
		return nil
	}
	out := new(BlueprintSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlueprintStatus) DeepCopyInto(out *BlueprintStatus) {
	*out = *in
	in.EffectiveBlueprint.DeepCopyInto(&out.EffectiveBlueprint)
	in.StateDiff.DeepCopyInto(&out.StateDiff)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlueprintStatus.
func (in *BlueprintStatus) DeepCopy() *BlueprintStatus {
	if in == nil {
		return nil
	}
	out := new(BlueprintStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentDiff) DeepCopyInto(out *ComponentDiff) {
	*out = *in
	out.Actual = in.Actual
	out.Expected = in.Expected
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentDiff.
func (in *ComponentDiff) DeepCopy() *ComponentDiff {
	if in == nil {
		return nil
	}
	out := new(ComponentDiff)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentDiffState) DeepCopyInto(out *ComponentDiffState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentDiffState.
func (in *ComponentDiffState) DeepCopy() *ComponentDiffState {
	if in == nil {
		return nil
	}
	out := new(ComponentDiffState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DoguDiff) DeepCopyInto(out *DoguDiff) {
	*out = *in
	out.Actual = in.Actual
	out.Expected = in.Expected
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DoguDiff.
func (in *DoguDiff) DeepCopy() *DoguDiff {
	if in == nil {
		return nil
	}
	out := new(DoguDiff)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DoguDiffState) DeepCopyInto(out *DoguDiffState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DoguDiffState.
func (in *DoguDiffState) DeepCopy() *DoguDiffState {
	if in == nil {
		return nil
	}
	out := new(DoguDiffState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectiveBlueprint) DeepCopyInto(out *EffectiveBlueprint) {
	*out = *in
	if in.Dogus != nil {
		in, out := &in.Dogus, &out.Dogus
		*out = make([]serializer.TargetDogu, len(*in))
		copy(*out, *in)
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]serializer.TargetComponent, len(*in))
		copy(*out, *in)
	}
	if in.RegistryConfig != nil {
		in, out := &in.RegistryConfig, &out.RegistryConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RegistryConfigAbsent != nil {
		in, out := &in.RegistryConfigAbsent, &out.RegistryConfigAbsent
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RegistryConfigEncrypted != nil {
		in, out := &in.RegistryConfigEncrypted, &out.RegistryConfigEncrypted
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectiveBlueprint.
func (in *EffectiveBlueprint) DeepCopy() *EffectiveBlueprint {
	if in == nil {
		return nil
	}
	out := new(EffectiveBlueprint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StateDiff) DeepCopyInto(out *StateDiff) {
	*out = *in
	if in.DoguDiffs != nil {
		in, out := &in.DoguDiffs, &out.DoguDiffs
		*out = make(map[string]DoguDiff, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ComponentDiffs != nil {
		in, out := &in.ComponentDiffs, &out.ComponentDiffs
		*out = make(map[string]ComponentDiff, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StateDiff.
func (in *StateDiff) DeepCopy() *StateDiff {
	if in == nil {
		return nil
	}
	out := new(StateDiff)
	in.DeepCopyInto(out)
	return out
}
