apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
  {{- include "k8s-blueprint-operator.labels" . | nindent 4 }}
  name: {{ include "k8s-blueprint-operator.name" . }}-blueprint-editor-role
rules:
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - blueprints
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - blueprints/status
    verbs:
      - get