apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
  {{- include "k8s-blueprint-operator.labels" . | nindent 4 }}
  name: {{ include "k8s-blueprint-operator.name" . }}-dogu-restart-role
rules:
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - dogurestarts
    verbs:
      - create
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - dogurestarts/status
    verbs:
      - get