apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "k8s-blueprint-operator.labels" . | nindent 4 }}
  name: {{ include "k8s-blueprint-operator.name" . }}-health-config
data:
  components: |
    {{- toYaml .Values.healthConfig.components | nindent 4 }}