# Issue RBAC permissions to the operator to fulfill CR handling which includes reading and updating customer-created
# Blueprint CRs. The operator does not create or delete Blueprints by itself, though.

apiVersion: rbac.authorization.k8s.io/v1
# the blueprint operator should only handle Blueprint CRs within its own namespace, not Blueprints in other namespaces
kind: Role
metadata:
  labels:
  {{- include "k8s-blueprint-operator.labels" . | nindent 4 }}
  name: {{ include "k8s-blueprint-operator.name" . }}-manager-role
rules:

# issue permissions to read/update fields beyond the status or finalizer fields
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - blueprints
    verbs:
      - get
      - list
      - patch
      - update
      - watch
# issue permissions to update the finalizer field that may control CR deletion
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - blueprints/finalizers
    verbs:
      - update
# issue permissions to update the status which contains blueprint processing data
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - blueprints/status
    verbs:
      - get
      - patch
      - update
# issue secret handling for Dogus
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
      - get
# issue PVC read-only permissions to amend the Blueprint CR with a currently configured Dogu volume size
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list