apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
  {{- include "k8s-blueprint-operator.labels" . | nindent 4 }}
  name: {{ include "k8s-blueprint-operator.name" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-blueprint-operator.name" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-blueprint-operator.name" . }}-sa
    namespace: '{{ .Release.Namespace }}'