apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
  {{- include "k8s-blueprint-operator.labels" . | nindent 4 }}
  name: {{ include "k8s-blueprint-operator.name" . }}-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create