apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
  {{- include "k8s-blueprint-operator.labels" . | nindent 4 }}
  name: {{ include "k8s-blueprint-operator.name" . }}-restore-reader-role
rules:
  - apiGroups:
      - k8s.cloudogu.com
    resources:
      - restores
    verbs:
      - get
      - list