// Code generated by mockery v2.20.0. DO NOT EDIT.

package doguregistry

import (
	core "github.com/cloudogu/cesapp-lib/core"
	mock "github.com/stretchr/testify/mock"
)

// mockCesappLibRemoteRegistry is an autogenerated mock type for the cesappLibRemoteRegistry type
type mockCesappLibRemoteRegistry struct {
	mock.Mock
}

type mockCesappLibRemoteRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCesappLibRemoteRegistry) EXPECT() *mockCesappLibRemoteRegistry_Expecter {
	return &mockCesappLibRemoteRegistry_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: dogu
func (_m *mockCesappLibRemoteRegistry) Create(dogu *core.Dogu) error {
	ret := _m.Called(dogu)

	var r0 error
	if rf, ok := ret.Get(0).(func(*core.Dogu) error); ok {
		r0 = rf(dogu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockCesappLibRemoteRegistry_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockCesappLibRemoteRegistry_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - dogu *core.Dogu
func (_e *mockCesappLibRemoteRegistry_Expecter) Create(dogu interface{}) *mockCesappLibRemoteRegistry_Create_Call {
	return &mockCesappLibRemoteRegistry_Create_Call{Call: _e.mock.On("Create", dogu)}
}

func (_c *mockCesappLibRemoteRegistry_Create_Call) Run(run func(dogu *core.Dogu)) *mockCesappLibRemoteRegistry_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*core.Dogu))
	})
	return _c
}

func (_c *mockCesappLibRemoteRegistry_Create_Call) Return(_a0 error) *mockCesappLibRemoteRegistry_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCesappLibRemoteRegistry_Create_Call) RunAndReturn(run func(*core.Dogu) error) *mockCesappLibRemoteRegistry_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: dogu
func (_m *mockCesappLibRemoteRegistry) Delete(dogu *core.Dogu) error {
	ret := _m.Called(dogu)

	var r0 error
	if rf, ok := ret.Get(0).(func(*core.Dogu) error); ok {
		r0 = rf(dogu)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockCesappLibRemoteRegistry_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockCesappLibRemoteRegistry_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - dogu *core.Dogu
func (_e *mockCesappLibRemoteRegistry_Expecter) Delete(dogu interface{}) *mockCesappLibRemoteRegistry_Delete_Call {
	return &mockCesappLibRemoteRegistry_Delete_Call{Call: _e.mock.On("Delete", dogu)}
}

func (_c *mockCesappLibRemoteRegistry_Delete_Call) Run(run func(dogu *core.Dogu)) *mockCesappLibRemoteRegistry_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*core.Dogu))
	})
	return _c
}

func (_c *mockCesappLibRemoteRegistry_Delete_Call) Return(_a0 error) *mockCesappLibRemoteRegistry_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCesappLibRemoteRegistry_Delete_Call) RunAndReturn(run func(*core.Dogu) error) *mockCesappLibRemoteRegistry_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: name
func (_m *mockCesappLibRemoteRegistry) Get(name string) (*core.Dogu, error) {
	ret := _m.Called(name)

	var r0 *core.Dogu
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*core.Dogu, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *core.Dogu); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Dogu)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockCesappLibRemoteRegistry_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockCesappLibRemoteRegistry_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - name string
func (_e *mockCesappLibRemoteRegistry_Expecter) Get(name interface{}) *mockCesappLibRemoteRegistry_Get_Call {
	return &mockCesappLibRemoteRegistry_Get_Call{Call: _e.mock.On("Get", name)}
}

func (_c *mockCesappLibRemoteRegistry_Get_Call) Run(run func(name string)) *mockCesappLibRemoteRegistry_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockCesappLibRemoteRegistry_Get_Call) Return(_a0 *core.Dogu, _a1 error) *mockCesappLibRemoteRegistry_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockCesappLibRemoteRegistry_Get_Call) RunAndReturn(run func(string) (*core.Dogu, error)) *mockCesappLibRemoteRegistry_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields:
func (_m *mockCesappLibRemoteRegistry) GetAll() ([]*core.Dogu, error) {
	ret := _m.Called()

	var r0 []*core.Dogu
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*core.Dogu, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*core.Dogu); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.Dogu)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockCesappLibRemoteRegistry_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type mockCesappLibRemoteRegistry_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *mockCesappLibRemoteRegistry_Expecter) GetAll() *mockCesappLibRemoteRegistry_GetAll_Call {
	return &mockCesappLibRemoteRegistry_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *mockCesappLibRemoteRegistry_GetAll_Call) Run(run func()) *mockCesappLibRemoteRegistry_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockCesappLibRemoteRegistry_GetAll_Call) Return(_a0 []*core.Dogu, _a1 error) *mockCesappLibRemoteRegistry_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockCesappLibRemoteRegistry_GetAll_Call) RunAndReturn(run func() ([]*core.Dogu, error)) *mockCesappLibRemoteRegistry_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function with given fields: name, version
func (_m *mockCesappLibRemoteRegistry) GetVersion(name string, version string) (*core.Dogu, error) {
	ret := _m.Called(name, version)

	var r0 *core.Dogu
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*core.Dogu, error)); ok {
		return rf(name, version)
	}
	if rf, ok := ret.Get(0).(func(string, string) *core.Dogu); ok {
		r0 = rf(name, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Dogu)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(name, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockCesappLibRemoteRegistry_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type mockCesappLibRemoteRegistry_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
//   - name string
//   - version string
func (_e *mockCesappLibRemoteRegistry_Expecter) GetVersion(name interface{}, version interface{}) *mockCesappLibRemoteRegistry_GetVersion_Call {
	return &mockCesappLibRemoteRegistry_GetVersion_Call{Call: _e.mock.On("GetVersion", name, version)}
}

func (_c *mockCesappLibRemoteRegistry_GetVersion_Call) Run(run func(name string, version string)) *mockCesappLibRemoteRegistry_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *mockCesappLibRemoteRegistry_GetVersion_Call) Return(_a0 *core.Dogu, _a1 error) *mockCesappLibRemoteRegistry_GetVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockCesappLibRemoteRegistry_GetVersion_Call) RunAndReturn(run func(string, string) (*core.Dogu, error)) *mockCesappLibRemoteRegistry_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersionsOf provides a mock function with given fields: name
func (_m *mockCesappLibRemoteRegistry) GetVersionsOf(name string) ([]core.Version, error) {
	ret := _m.Called(name)

	var r0 []core.Version
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]core.Version, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []core.Version); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Version)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockCesappLibRemoteRegistry_GetVersionsOf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersionsOf'
type mockCesappLibRemoteRegistry_GetVersionsOf_Call struct {
	*mock.Call
}

// GetVersionsOf is a helper method to define mock.On call
//   - name string
func (_e *mockCesappLibRemoteRegistry_Expecter) GetVersionsOf(name interface{}) *mockCesappLibRemoteRegistry_GetVersionsOf_Call {
	return &mockCesappLibRemoteRegistry_GetVersionsOf_Call{Call: _e.mock.On("GetVersionsOf", name)}
}

func (_c *mockCesappLibRemoteRegistry_GetVersionsOf_Call) Run(run func(name string)) *mockCesappLibRemoteRegistry_GetVersionsOf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockCesappLibRemoteRegistry_GetVersionsOf_Call) Return(_a0 []core.Version, _a1 error) *mockCesappLibRemoteRegistry_GetVersionsOf_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockCesappLibRemoteRegistry_GetVersionsOf_Call) RunAndReturn(run func(string) ([]core.Version, error)) *mockCesappLibRemoteRegistry_GetVersionsOf_Call {
	_c.Call.Return(run)
	return _c
}

// SetUseCache provides a mock function with given fields: useCache
func (_m *mockCesappLibRemoteRegistry) SetUseCache(useCache bool) {
	_m.Called(useCache)
}

// mockCesappLibRemoteRegistry_SetUseCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUseCache'
type mockCesappLibRemoteRegistry_SetUseCache_Call struct {
	*mock.Call
}

// SetUseCache is a helper method to define mock.On call
//   - useCache bool
func (_e *mockCesappLibRemoteRegistry_Expecter) SetUseCache(useCache interface{}) *mockCesappLibRemoteRegistry_SetUseCache_Call {
	return &mockCesappLibRemoteRegistry_SetUseCache_Call{Call: _e.mock.On("SetUseCache", useCache)}
}

func (_c *mockCesappLibRemoteRegistry_SetUseCache_Call) Run(run func(useCache bool)) *mockCesappLibRemoteRegistry_SetUseCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *mockCesappLibRemoteRegistry_SetUseCache_Call) Return() *mockCesappLibRemoteRegistry_SetUseCache_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockCesappLibRemoteRegistry_SetUseCache_Call) RunAndReturn(run func(bool)) *mockCesappLibRemoteRegistry_SetUseCache_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockCesappLibRemoteRegistry interface {
	mock.TestingT
	Cleanup(func())
}

// newMockCesappLibRemoteRegistry creates a new instance of mockCesappLibRemoteRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockCesappLibRemoteRegistry(t mockConstructorTestingTnewMockCesappLibRemoteRegistry) *mockCesappLibRemoteRegistry {
	mock := &mockCesappLibRemoteRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
